'(("You arrive at the coordinates of the hidden stash of atomics..." . "Llegas a las coordenadas del alijo oculto de atómicas...")
("You arrive, but the princess looks troubled..." . "Llegas, pero la princesa parece preocupada...")
("<c:Warrior Princess of E. Cay:28>Since shortly after we departed, I haven't been able to contact anyone back home. <B:0> I have instructions, if our kingdom is overrun, to activate the atomics and use them to avenge my people's deaths. Please accept this:" . "<c:Princesa Guerrera de E. Cay:28>Desde poco después de que partiéramos, no he podido contactar con nadie en casa. <B:0> Tengo instrucciones, si nuestro reino es invadido, de activar las atómicas y usarlas para vengar la muerte de mi pueblo. Por favor acepta esto:")
("[You write down the launch codes...]" . "[Anotas los códigos de lanzamiento...]")
("<c:Warrior Princess of E. Cay:28>Now, be very careful when moving them..." . "<c:Princesa Guerrera de E. Cay:28>Ahora, ten mucho cuidado al moverlas...")
("Place weapon (1x2)" . "Colocar arma (1x2)")
("You retrieved an atomic missile! There were others, but only one was still functioning." . "¡Recuperaste un misil atómico! Había otros, pero solo uno aún funcionaba.")
("<c:Warrior Princess of E. Cay:28>Those goblins will be sorry they crossed us!" . "<c:Princesa Guerrera de E. Cay:28>¡Esos goblins se arrepentirán de haberse cruzado con nosotros!")
)
