'(("You arrive at the coordinates marked in the ancient texts..." . "Llegas a las coordenadas marcadas en los textos antiguos...")
("You arrive, but the Ashwalker Apprentice seems disturbed..." . "Llegas, pero el aprendiz Ashwalker parece perturbado...")
("<c:Ashwalker Apprentice:41>The Order's chants... they've gone ssssilent. <B:0> Our ritualsss teach that if the Order falls, we must use the old weaponsss to take retribution against our enemies. Take thisss:" . "<c:Aprendiz Ashwalker:41>Losss cánticosss de la Orden... han enmudecido. <B:0> Nuestrosss ritualesss enseñan que sssi la Orden cae, debemosss usar lasss armasss antiguasss para tomar represaliasss contra nuestrosss enemigosss. Toma esssto:")
("[You write down the launch codes...]" . "[Anotas los códigos de lanzamiento...]")
("<c:Ashwalker Apprentice:41>Handle with care... the radiation still singsss.." . "<c:Aprendiz Ashwalker:41>Manéjalo con cuidado... la radiación aún canta...")
("Place weapon (1x2)" . "Colocar arma (1x2)")
("You retrieved an atomic missile! There were others, but only one was still functioning." . "¡Recuperaste un misil atómico! Había otros, pero solo uno aún funcionaba.")
("<c:Ashwalker Apprentice:41>Now they'll learn why even the ssstorm fears usss!" . "<c:Aprendiz Ashwalker:41>¡Ahora aprenderán por qué hasssta la tormenta nosss teme!")
)
