'(("<c:Goblin Pirates:2>We sssurrender! Honessst, we promise to help you pillage any other cassstles!" . "<c:Piratas Goblin:2>¡Nosss rendimosss! ¡En ssserio, prometemosss ayudarosss a saquear cualquier otro cassstillo!")
("<c:Goblin Pirates:2>We sssurrender! Honessst, we promise not to pillage any other cassstles!" . "<c:Piratas Goblin:2>¡Nosss rendimosss! ¡En ssserio, prometemosss no saquear ningún otro cassstillo!")
("The goblins offer surrender, accept terms?" . "Los goblins ofrecen rendirse, ¿aceptar los términos?")
("+1 crew, +%@" . "+1 tripulante, +%@")
("<c:Goblin:18>Gahh! <B:0> You are out of ssspace! <B:0> Nice friendsss will not leave usss! I'll build an ledarr!" . "<c:Goblin:18>¡Gahh! <B:0> ¡No tenesss sssitio! <B:0> ¡Amigosss amablesss no nosss dejarán! ¡Consstruiré una esscalela!")
("<c:Goblin:18>Gahh! <B:0> You are out of ssspace! <B:0> Nice humansss will not leave usss! I'll build an ledarr!" . "<c:Goblin:18>¡Gahh! <B:0> ¡No tenesss sssitio! <B:0> ¡Humanosss amablesss no nosss dejarán! ¡Consstruiré una esscalela!")
("Place block (1x2):" . "Colocar bloque (1x2):")
("One of the goblins joined your crew!" . "¡Uno de los goblins se unió a tu tripulación!")
("While scanning the goblin fortress' computers, you find some fascinating images of the surface world. You record them on a cartridge..." . "Al escanear los ordenadores de la fortaleza goblin, encuentras unas imágenes fascinantes del mundo de la superficie. Las grabas en un cartucho...")
("Salvage rights: % blocks." . "Derechos de desguace: % bloques.")
("Take block: (%/%)" . "Tomar bloque: (%/%)")
("This will remove the island's only power source, causing it to become unstable (you won't be able to take any more blocks), are you sure?" . "Esto eliminará la única fuente de energía de la isla, volviéndola inestable (no podrás tomar más bloques), ¿estás seguro?")
("Place block:" . "Colocar bloque:")
("Place block: (%/%)" . "Colocar bloque: (%/%)")
("Accepted surrender, and acquired % blocks!" . "¡Rendición aceptada, y adquiridos % bloques!")
("Unacceptable! (+%@)" . "¡Inaceptable! (+%@)")
)
