
(map
 (lambda (syscall "setvar" (cdr $0) (car $0)))
 '((5   . "mcr_ice_cost")
   (5   . "mcr_shrubbery_cost")
   (5   . "mcr_road_cost")
   (30  . "mcr_water_cost")
   (30  . "mcr_masonry_cost")
   (30  . "mcr_sand_cost")
   (30  . "mcr_scaffolding_cost")
   (40  . "mcr_wheat_cost")
   (40  . "mcr_arch_cost")
   (80  . "mcr_windmill_cost")
   (90  . "mcr_lumber_cost")
   (100 . "mcr_terrain_cost")
   (120 . "mcr_indigo_cost")
   (120 . "mcr_madder_cost")
   (120 . "mcr_shellfish_cost")
   (120 . "mcr_tulips_cost")
   (120 . "mcr_sunflowers_cost")
   (150 . "mcr_windmill_stone_base_cost")
   (200 . "mcr_light_source_cost")
   (200 . "mcr_port_cost")
   (270 . "mcr_potatoes_cost")
   (270 . "mcr_building_cost")
   (300 . "mcr_cocoa_cost")
   (300 . "mcr_tea_cost")
   (300 . "mcr_pearls_cost")
   (410 . "mcr_wool_cost")
   (410 . "mcr_honey_cost")
   (460 . "mcr_saffron_cost")
   (700 . "mcr_workshop_cost")
   (800 . "mcr_lava_cost")
   (1000 . "mcr_marble_cost")
   (4000 . "mcr_gold_cost")
   (9000 . "mcr_crystal_cost")

   (2 . "mcr_food_consumption_factor")
   (85 . "mcr_commodity_diminishing_return_percent")))


(gc)
