
(map
 (lambda (syscall "setvar" (string "mcr_" (cdr $0)) (car $0)))
 '((5   . "ice_cost")
   (5   . "shrubbery_cost")
   (5   . "road_cost")
   (30  . "water_cost")
   (30  . "masonry_cost")
   (30  . "sand_cost")
   (30  . "scaffolding_cost")
   (40  . "wheat_cost")
   (40  . "arch_cost")
   (80  . "windmill_cost")
   (90  . "lumber_cost")
   (100 . "terrain_cost")
   (120 . "indigo_cost")
   (120 . "madder_cost")
   (120 . "shellfish_cost")
   (120 . "tulips_cost")
   (120 . "sunflowers_cost")
   (150 . "windmill_stone_base_cost")
   (200 . "light_source_cost")
   (200 . "port_cost")
   (270 . "potatoes_cost")
   (270 . "building_cost")
   (300 . "cocoa_cost")
   (300 . "tea_cost")
   (300 . "pearls_cost")
   (410 . "wool_cost")
   (410 . "honey_cost")
   (460 . "saffron_cost")
   (700 . "workshop_cost")
   (400 . "lava_cost")
   (1000 . "marble_cost")
   (4000 . "gold_cost")
   (9000 . "crystal_cost")

   (40 . "base_seconds_per_year")
   (5 . "added_seconds_per_year_per_island")

   (2 . "food_consumption_factor")
   (85 . "commodity_diminishing_return_percent")
   (37 . "employment_yield_percent")
   (10 . "jobless_yield_percent")
   (40 . "homelessness_penalty_percent")
   (40 . "starvation_penalty_percent")
   (25 . "pop_growth_food_surplus_percent")
   (50 . "pop_growth_food_shortage_percent")
   (25 . "pop_growth_housing_factor")))

(gc)
