'(("You approach a raider waypoint. A goblin crew broadcasts a signal requesting help..." . "Te acercas a un punto de encuentro de asaltantes. Una tripulación goblin emite una señal pidiendo ayuda...")
("<c:Raider:39>Sssnatched some valuable cargo from a merchant fleet, but our ship took heavy damage in the fight. With that ssstorm approaching, we won't make it to the black market in time. Help usss deliver the goods? We'll sssplit the profit, and our contact paysss well!" . "<c:Asaltante:39>Le arrebatamosss carga valiosa a una flota mercante, pero nuestro barco quedó muy dañado en la pelea. Con esa tormenta acercándossse, no llegaremosss al mercado negro a tiempo. ¿Nos ayudáisss a entregar la mercancía? ¡Nosss repartimosss las ganancias, y nuestro contacto paga bien!")
("I accept!" . "¡Acepto!")
("Sorry, but no." . "Lo siento, pero no.")
("loot" . "botín")
("<c:raider:39>Excccellent! I'll mark the location with an * on your chart!" . "<c:Asaltante:39>¡Excccelente! ¡Marcaré la ubicación con un * en tu carta!")
("<c:Raider:39>Bah! Jussst got word our contact had to move their operation - ssstorm's getting too close. Here'sss 400@ for your time, at leassst." . "<c:Asaltante:39>¡Bah! Acabo de enterarme de que nuessstro contacto tuvo que mover la operación - la tormenta ssse acerca demasiado. Aquí tienesss 400@ por tu tiempo, al menosss.")
("<c:Raider:39>Bah, fine... We'll find another sssship to move the loot..." . "<c:Asaltante:39>Bah, vale... Encontraremosss otro barco para mover el botín...")
)
