'(("You encounter a goblin salvage crew hauling up strange artifacts through a break in the clouds. Your crew recognizes them as valuable relics from the surface wars..." . "Te encuentras con una cuadrilla goblin de salvamento izando extraños artefactos a través de una abertura en las nubes. Tu tripulación los reconoce como valiosas reliquias de las guerras de la superficie...")
("<c:Scavenger:34>Found thessse rare artifactsss in the ruinsss below! Worth a fortune to the right collector. Only %@ for the lot!" . "<c:Carroñero:34>¡Encontré estasss reliquiasss rarasss en lasss ruinasss de abajo! Valen una fortuna para el colecccionissta adecuado. ¡Sssolo %@ por el lote!")
("OK!" . "¡Vale!")
("No thanks." . "No, gracias.")
("artifacts" . "artefactos")
("<c:Scavenger:34>Careful with the ancient tech!" . "<c:Carroñero:34>¡Cuidado con la tecnología antigua!")
("(Your crew marks a collector's location on your sky chart with an *)" . "(Tu tripulación marca la ubicación de un coleccionista en tu carta del cielo con un *)")
("<c:Scavenger:34>Bah, sssomeone else already claimed the artifactsss..." . "<c:Carroñero:34>Bah, alguien ya reclamó losss artefactosss...")
("<c:Scavenger:34>Argh, off with you then!" . "<c:Carroñero:34>¡Argh, largarosss entoncccesss!")
)
