'(("You discover the ruins of an ancient civilization. " . "Descubres las ruinas de una antigua civilización. ")
("The island appears deserted, but just as you are about to leave, someone signals for help..." . "La isla parece desierta, pero justo cuando estás a punto de irte, alguien pide ayuda...")
("A small injured boy begins speaking softly in an archaic language..." . "Un niño pequeño y herido comienza a hablar suavemente en un idioma arcaico...")
("<c:Injured Boy:26> " . "<c:Niño Herido:26> ")
("You can't understand a word he's saying. But he seems to want to join your crew.<B:0> Invite him aboard?" . "No entiendes ni una palabra de lo que dice. Pero parece querer unirse a tu tripulación.<B:0> ¿Invitarlo a bordo?")
("Yes." . "Sí.")
("I'll pass." . "Paso.")
("Who might he be?" . "¿Quién será?")
("He looks like he might be a Sylph child. They've been up here a long time, but not much is known about them. <B:0> Invite him aboard?" . "Parece que podría ser un niño sylph. Llevan mucho tiempo aquí arriba, pero no se sabe mucho sobre ellos. <B:0> ¿Invitarlo a bordo?")
("The orphan boy joined your crew! <B:0> Upon discovering your sky chart, he marked a location with an *..." . "¡El niño huérfano se unió a tu tripulación! <B:0> Al descubrir tu carta del cielo, marcó una ubicación con un *...")
("The injured boy joined your crew! Wonder where he came from..." . "¡El niño herido se unió a tu tripulación! Quién sabe de dónde vendrá...")
)
