'(("A proximity alarm wakes your crew in the night! <B:0>" . "¡Una alarma de proximidad despierta a tu tripulación en la noche! <B:0>")
("An ancient fortress appears in the moonlight. <B:0>" . "Una antigua fortaleza aparece a la luz de la luna. <B:0>")
("You almost ran right into it! Inside, you hear the sounds of ritual chanting..." . "¡Casi chocas contra ella! En su interior, oyes sonidos de cánticos rituales...")
("<c:Ashwalker Elder:42>The ssstorm brings change... Our seers have had visionsss of an ancient weapon, buried in the ruinsss of our ancestorsss. <B:0> A relic from before the Great Change that made usss what we are... <B:0> It must not remain below when the ssstorm arrives. <B:0> Will you help retrieve it?" . "<c:Anciano Ashwalker:42>La tormenta trae cambiosss... Nuestrosss videntesss han tenido visionesss de un arma antigua, enterrada en lasss ruinasss de nuestrosss ancestrosss. <B:0> Una reliquia de antes del Gran Cambio que nosss hizo lo que sssomosss... <B:0> No debe permanecer abajo cuando llegue la tormenta. <B:0> ¿Nosss ayudaréisss a recuperarla?")
("Okay..." . "Vale...")
("Sssorry, but no." . "Lo sssiento, pero no.")
("<c:Ashwalker Elder:42> The location hasss been marked on your chart with an *! <B:0> My apprentice will guide you through the old rituals..." . "<c:Anciano Ashwalker:42> ¡La ubicación ha sssido marcada en tu carta con un *! <B:0> Mi aprendiz osss guiará a travésss de losss ritualesss antiguosss...")
("<c:Ashwalker Apprentice:41> Finally, a chance to prove my worth to the Order! <B:0> I know all the ancient wardsss against radiation!" . "<c:Aprendiz Ashwalker:41> ¡Por fin, una oportunidad de demosssstrar mi valía ante la Orden! <B:0> ¡Conozco todosss losss conjurosss antiguosss contra la radiación!")
("<c:Ashwalker Apprentice:41> Hmm... you ssseem to be out of ssspace... <B:0> Let me fix that!" . "<c:Aprendiz Ashwalker:41> Hmm... parece que no tenesss sssitio... <B:0> ¡Dejad que lo arregle!")
("Place block (1x2):" . "Colocar bloque (1x2):")
("The apprentice joined your crew!" . "¡El aprendiz se unió a tu tripulación!")
("<c:Ashwalker Elder:42>The visionsss were unclear... The ssstorm movesss too quickly, the path isss already blocked..." . "<c:Anciano Ashwalker:42>Lasss visionesss no eran clarasss... La tormenta avanza demasiado rápido, el camino ya essstá bloqueado...")
)
