#pragma once



struct StaticTile
{
    // These tiles are not dynamically re-mappable. They live at fixed positions
    // at the beginning of the tile set.
    enum {
        null,
        airborne_selection = 1,
        flag_start = 2,
        flag_end = 5,
        group_icons,
        path_marker,
        count,
    };
};



struct Tile
{
    enum {
        null,
        airborne_selection = 1,
        flag_start = 2,
        flag_end = 5,
        __fixme,
        __fixme2,
        palm_1,
        palm_2,
        shrubbery,
        ion_fizzler_exterior = 11,
        terrain_middle,
        terrain_left,
        terrain_right,
        wall_window_1,
        wall_window_2,
        wall_plain_1,
        wall_plain_2,
        roof_plain,
        roof_chimney,
        cannon_1,
        armored_wall_1,
        armored_wall_2,
        roof_plain_intersect_armored_wall,
        wall_window_middle_1,
        wall_window_middle_2,
        grass,
        reserved_1,
        hull,
        wall_plain_middle,
        reserved_3,
        reserved_4,
        reserved_5,
        reserved_6,
        missile_silo_1,
        missile_silo_2,
        forcefield,
        reserved7,
        reserved8,
        reserved9,
        reserved10,
        tin_chimney,
        plundered_room,
        reserved_11,
        reserved_12,
        radar_1,
        radar_2,
        reserved_13,
        reserved_14,
        reserved_15,
        reserved_16,
        particle_gun,
        reserved_17,
        reserved_18,
        reserved_19,
        reserved_20,
        reserved_21,
        flak_gun_1,
        flak_gun_2,
        drone_bay_1,
        drone_bay_2,
        decimator_1,
        decimator_2,
        reserved_22,
        reserved_23,
        reserved_24,
        reserved_25,
        reserved_26,
        field_hull,
        ion_fizzler,
        reserved_27,
        reserved_28,
        reserved_29,
        reserved_30,
        reserved_31,
        reserved_32,
        arc_gun,
        masonry,
        statue_1,
        statue_2,
        bridge,
        nemesis_1,
        nemesis_2,
        bronze,
        dynamite,
        tnt,
        reserved_33,
        synth,
        speaker_inactive,
        speaker_active,
        radiator,
        switch_1,
        switch_on,
        switch_off,
        banana_plant,
        roof_flag,
        flag_mount,
        sunflower,
        fountain,
        bridge_truss,

        // All tile indices below are reserved for DLC content.
        dlc_tiles_begin = 113,
    };
};



struct InteriorTile
{
    enum {
        null,
        airborne_selection = 1,
        flag_start = 2,
        flag_end = 5,
        __fixme,
        __fixme2,
        palm_1,
        palm_2,
        shrubbery,
        ion_fizzler_interior = 11,
        core_1 = 15,
        core_2,
        core_3,
        core_4,
        roof_1,
        roof_2,
        cannon_1,
        ladder_base,
        ladder_mid,
        roof_3,
        __unused__,
        ladder_top,
        grass,
        empty,
        hull,
        workshop_1,
        workshop_2,
        workshop_3,
        workshop_4,
        __unused2__,
        missile_silo_1,
        missile_silo_2,
        forcefield,
        infirmary_1,
        infirmary_3,
        infirmary_2,
        infirmary_4,
        tin_chimney,
        plundered_room,
        transporter_1,
        transporter_2,
        radar_1,
        radar_2,
        bulkhead_closed_1,
        bulkhead_closed_2,
        bulkhead_open_1,
        plain_floor,
        particle_gun,
        transporter_recharge,
        replicator_1,
        replicator_2,
        replicator_3,
        replicator_4,
        flak_gun_1,
        flak_gun_2,
        drone_bay_1,
        drone_bay_2,
        decimator_1,
        decimator_2,
        decimator_int,
        reactor_1,
        reactor_2,
        reactor_3,
        reactor_4,
        field_hull,
        ion_fizzler,
        manufactory_1,
        manufactory_2,
        manufactory_3,
        manufactory_4,
        manufactory_5,
        cargo_bay,
        arc_gun,
        masonry,
        statue_1,
        statue_2,
        bridge,
        nemesis_1,
        nemesis_2,
        bronze,
        dynamite,
        tnt,
        __unused3__,
        synth,
        speaker_inactive,
        speaker_active,
        radiator,
        switch_1,
        switch_on,
        switch_off,
        banana_plant,
        roof_flag,
        flag_mount,
        sunflower,
        fountain,
        bridge_truss,

        // All tile indices below are reserved for DLC content.
        dlc_tiles_begin = 113,
    };
};


struct SpriteTile
{
    enum {
        custom_sprite_tile_begin = 110,
    };
};
