'(("1: Goliath" . "1: Goliat")
("2: Goblin Raid" . "2: Incursión Goblin")
("3: Nemesis" . "3: Némesis")
("4: Masonry" . "4: Mampostería")
("5: Mycelium!" . "5: ¡Micelio!")
("6: Porcupine 1" . "6: Puercoespín 1")
("7: Porcupine 2" . "7: Puercoespín 2")
("8: Highwater" . "8: Pleamar")
("9: Arc Defense" . "9: Defensa de Arco")
("10: Pursuit" . "10: Persecución")
("11: Exchange" . "11: Intercambio")
("12: Demolition" . "12: Demolición")
("13: Fire Brigade" . "13: Brigada de Incendios")
)
