'(("Hah! You can't afford that!" . "¡Ja! ¡No te alcanza!")
("<c:Shopkeeper:7>%? I'll sell you one for %@..." . "<c:Tendero:7>¿%? Te vendo uno por %@...")
("I'll buy it!" . "¡Lo compro!")
("Pick a slot:" . "Elige un espacio:")
("<c:Shopkeeper:7>How am I supposed to keep customers if you buy the whole store!? <B:0> WE'RE CLOSED." . "<c:Tendero:7>¡¿Cómo voy a mantener clientes si te compras toda la tienda!? <B:0> ESTAMOS CERRADOS.")
("% stats?" . "ver %")
("describe %" . "¿estadísticas de %?")
("No thanks…" . "No, gracias…")
("<c:Shopkeeper:7>What would you like to do?" . "<c:Tendero:7>¿Qué te gustaría hacer?")
("shop" . "comprar")
("repair" . "reparar")
("<c:Shopkeeper:7>Let me have my repairman come over and assess the damages..." . "<c:Tendero:7>Deja que mi mecánico venga a evaluar los daños...")
("retune core" . "reafinar núcleo")
("<c:Shopkeeper:7>Core service, eh? Well... I've got this Sylph fellow who showed up last week. Bit odd, claims he can 'retune' your power matrix or some such..." . "<c:Tendero:7>¿Servicio de núcleo, eh? Bueno... tengo a un tipo sylph que apareció la semana pasada. Un poco raro, dice que puede 'reafinar' tu matriz de energía o algo así...")
("chat" . "charlar")
("<c:Shopkeeper:7>One piece of news that I learned today is: " . "<c:Tendero:7>Una novedad que me enteré hoy es: ")
("<B:0> Interesting, huh?" . "<B:0> Interesante, ¿no?")
("back" . "volver")
("<c:Shopkeeper:7>Welcome to my shop! Let me know if you see anything you like! (When done, use the START menu to return to your sky chart!)" . "<c:Tendero:7>¡Bienvenido a mi tienda! ¡Dime si ves algo que te guste! (¡Cuando termines, usa el menú START para volver a tu carta del cielo!)")
)
