'(("In the distance, you see an island inhabited by a lone castaway..." . "A lo lejos, divisas una isla habitada por un náufrago solitario...")
("Days stranded: |||| |||| |||| |||| ||||..." . "Días varado: |||| |||| |||| |||| ||||...")
("<c:Castaway:1>Fancy meeting you here! I've been marooned on this island... who knows how long! Looks like a nasty storm's brewing, mind if I hitch a ride?" . "<c:Náufrago:1>¡Vaya encuentro! Llevo varado en esta isla... ¡quién sabe cuánto tiempo! Parece que se avecina una tormenta terrible, ¿me lleváis con vosotros?")
("He seems harmless, invite him aboard?" . "Parece inofensivo, ¿invitarle a bordo?")
("Welcome aboard!" . "¡Bienvenido a bordo!")
("Not today." . "Hoy no.")
("How'd you get here?" . "¿Cómo llegaste aquí?")
("<c:Castaway:1>I was travelling on an airship that got boarded by goblins. I panicked and jumped in a transporter. I guess things could have turned out much worse, heh. <B:0> Wanna join up?" . "<c:Náufrago:1>Viajaba en un dirigible cuando lo abordaron los goblins. Entré en pánico y salté a un transportador. Supongo que podría haber sido mucho peor, je. <B:0> ¿Queréis que me una?")
("The castaway joined your crew. Starving, he ate 300@ of your food supplies!" . "El náufrago se unió a tu tripulación. ¡Muerto de hambre, devoró 300@ de tus provisiones!")
("Sadly, there's no room..." . "Lamentablemente, no hay espacio...")
("<c:Castaway:1>Hold on, don't leave me here! I may not meet anyone else for a long time... I'll help you build an addition onto your castle, then there'll be enough space for me to sleep! Let's see... I've got just enough supplies to build a ladder..." . "<c:Náufrago:1>¡Espera, no me dejéis aquí! Puede que no encuentre a nadie en mucho tiempo... ¡Os ayudaré a ampliar el castillo, así habrá sitio para que duerma! A ver... tengo justo los materiales para construir una escalera...")
("Place ladder (1x2):" . "Colocar escalera (1x2):")
("<c:Castaway:1> Thanks for rescuing me! I'll try to help out however I can!" . "<c:Náufrago:1> ¡Gracias por rescatarme! ¡Intentaré ayudar en lo que pueda!")
("The castaway joined your crew!" . "¡El náufrago se unió a tu tripulación!")
)
