'(("In the distance, you see an island inhabited by a lone castaway..." . "A lo lejos, ves una isla habitada por un náufrago solitario...")
("Days stranded: |||| |||| |||| |||| ||||..." . "Días varado: |||| |||| |||| |||| ||||...")
("<c:Castaway:27>Argh. I'm in a tough spot here. After years of fighting goblins, my crew mutinied and left me stranded here. <B:0> At least they picked an island with food, but I'm getting so fed up with eating coconuts and bananas!" . "<c:Náufrago:27>Argh. Estoy en una situación difícil. Después de años luchando contra duendes, mi tripulación se amotinó y me dejaron varado aquí. <B:0> Al menos eligieron una isla con comida, ¡pero ya estoy harto de comer cocos y plátanos!")
("He seems harmless, invite him aboard?" . "Parece inofensivo, ¿invitarlo a bordo?")
("Sadly, there's no room..." . "Lamentablemente, no hay espacio...")
("<c:Castaway:27>Hold on, don't leave me here! I may not meet anyone else for a long time... I'll help you build an addition onto your castle, then there'll be enough space for me to sleep! Let's see... I've got just enough supplies to build a ladder..." . "<c:Náufrago:27>¡Espera, no me dejes aquí! Puede que no me encuentre con nadie en mucho tiempo... ¡Te ayudaré a construir una ampliación en tu castillo, así habrá espacio para que yo duerma! A ver... tengo justo los materiales para construir una escalera...")
("Place ladder (1x2):" . "Colocar escalera (1x2):")
("<c:Castaway:27> Thanks for rescuing me! I'll try to help out however I can!" . "<c:Náufrago:27> ¡Gracias por rescatarme! ¡Intentaré ayudar en lo que pueda!")
("The castaway joined your crew!" . "¡El náufrago se unió a tu tripulación!")
)
