'(("In the distance, you see an island inhabited by a lone castaway..." . "A lo lejos, ves una isla habitada por un náufrago solitario...")
("Days stranded: |||| |||| |||| |||| ||||..." . "Días varado: |||| |||| |||| |||| ||||...")
("<c:Castaway:38>Yargh!! About time sssomeone showed up! <B:0> I don't even know how long I've been ssstranded here. I've been kicked out of the goblin horde, how could they do this!?" . "<c:Náufrago:38>¡¡Yargh!! ¡Ya era hora de que apareciessse alguien! <B:0> Ni sssé cuánto tiempo llevo varado aquí. ¡Me echaron de la horda goblin, cómo pudieron hacerme esssto!?")
("He seems decent, invite him aboard?" . "Parece decente, ¿invitarlo a bordo?")
("Welcome aboard!" . "¡Bienvenido a bordo!")
("Not today." . "Hoy no.")
("what happened?" . "¿qué pasó?")
("<c:Castaway:38> We were given ordersss to raid a human ssship. <B:0> Nothing ssspecial. For sssome reason I hesssitated, and was thrown overboard. <B:0> I can make amendsss, I'll show you, I'm ssstill vicious, I ssswear!" . "<c:Náufrago:38> Nos dieron órdenesss de asaltar una nave humana. <B:0> Nada del otro mundo. Por alguna razón dudé un momento, y me lanzaron por la borda. <B:0> ¡Puedo compensssarlo, ya veréisss, sssigo sssiendo feroz, lo juro!")
("<c:Castaway:38>Hold on, don't leave me here! I know your cassstle's full, but I can help make some ssspace!" . "<c:Náufrago:38>¡Essspera, no me dejesss aquí! Sé que tu cassstillo está lleno, ¡pero puedo ayudar a hacer sssitio!")
("Place block (1x2):" . "Colocar bloque (1x2):")
("<c:Castaway:38> Thanks for ressscuing me! I'll try to help out however I can! <B:0> ... <B:0> What? You've been banissshed too? <B:0> Ha! <a:LAUGH>HAHAHA! Sssome sssorry lot of goblinsss we are!" . "<c:Náufrago:38> ¡Graciasss por ressscatarme! ¡Intentaré ayudar en lo que pueda! <B:0> ... <B:0> ¿Qué? ¿A ti también te desssterraron? <B:0> ¡Ja! ¡<a:LAUGH>JAJAJA! ¡Vaya pandilla de goblinsss patéticosss que sssomosss!")
("The castaway joined your crew!" . "¡El náufrago se unió a tu tripulación!")
("The castaway joined your crew. Starving, he ate 300@ of your food supplies!" . "El náufrago se unió a tu tripulación. ¡Muerto de hambre, devoró 300@ de tus provisiones!")
)
