'(("A heavily armed marauder fortress approaches. Its captain demands to speak with you." . "Una fortaleza merodeadora fuertemente armada se acerca. Su capitán exige hablar contigo.")
("<c:goblin:2>Yesss captain!" . "<c:goblin:2>¡Sssí capitán!")
("(the transmission was cut)" . "(la transmisión se cortó)")
("<c:Redbeard:12>Yaargh!! I'm just a simple marauder, trying to earn a decent living here! [via petty extortion, how else?] <B:0> So what's it gonna be? Last chance..." . "<c:Barbarroja:12>¡¡Yaargh!! ¡Soy un simple merodeador, intentando ganarme la vida honradamente! [mediante pequeñas extorsiones, ¿cómo si no?] <B:0> Bueno, ¿qué va a ser? Última oportunidad...")
("Pay 600@." . "Pagar 600@.")
("Fight back." . "¡Luchar!")
("<c:Redbeard:12>Negotiate!? Ha. <d:1000> Hahahah! <d:1000> The only negotiation will be how fast you pay me!" . "<c:Barbarroja:12>¿¡Negociar!? Ja. <d:1000> ¡Jajajaj! <d:1000> ¡La única negociación será lo rápido que me pagues!")
("<c:Redbeard:12>Aarrrgh!! You're trespassing in my domain. Gimme 600@ or I'll blast your island to bits!" . "<c:Barbarroja:12>¡¡Aarrrgh!! Estás invadiendo mi dominio. ¡Dame 600@ o haré pedazos tu isla!")
("Here's 600@…" . "Aquí tienes 600@…")
("You're bluffing!" . "¡Estás faroleando!")
("Let's negotiate!" . "¡Negociemos!")
("Never!" . "¡Jamás!")
("<c:redbeard:12>That's not enough, load the cannons!!!" . "<c:Barbarroja:12>¡¡¡No es suficiente, cargad los cañones!!!")
("<c:redbeard:12>Heh. I think you made the smart decision." . "<c:Barbarroja:12>Jeh. Creo que tomaste la decisión inteligente.")
("<c:redbeard:12>Whaatt!! Load the cannons!!!" . "<c:Barbarroja:12>¡¡¡Quéee!! ¡¡¡Cargad los cañones!!!")
("<c:Redbeard:12>Alright, alright! You've bested me! I yield! <B:0> You've disarmed the great Redbeard without sinking him - not many can claim that. <B:0> Take what you want from my hold, just... leave me vessel intact, aye?" . "<c:Barbarroja:12>¡Está bien, está bien! ¡Me habéis vencido! ¡Me rindo! <B:0> Habéis desarmado al gran Barbarroja sin hundirlo - no muchos pueden presumir de eso. <B:0> Coged lo que queráis de mi bodega, solo... dejad mi nave intacta, ¿eh?")
("Among the scattered coins and looted cargo, you find a battered data cartridge, its label barely legible. <B:0> Redbeard waves dismissively. 'Old stories, mostly lies. Take it if you want.'" . "Entre las monedas dispersas y la carga saqueada, encuentras un cartucho de datos maltrecho, con la etiqueta apenas legible. <B:0> Barbarroja hace un gesto desdeñoso. 'Viejas historias, casi todo mentiras. Llévatelo si quieres.'")
)
