'(("A small but heavily fortified island appears on your scanners. Scattered debris floats nearby - twisted metal and charred wood from recent conflicts..." . "Una isla pequeña pero fuertemente fortificada aparece en tus escáneres. Restos dispersos flotan cerca - metal retorcido y madera carbonizada de conflictos recientes...")
("Your opponent has locked weapons, prepare for battle!" . "¡Tu oponente ha fijado armas, prepárate para la batalla!")
("<c:Anvil Annie:44>Broke, eh? Well, Sweet Bertha doesn't work for free! Time to collect your scrap as payment instead!" . "<c:Annie Yunque:44>¿Sin blanca, eh? ¡Pues la dulce Bertha no trabaja gratis! ¡Hora de cobrarme con tu chatarra!")
("<c:Anvil Annie:44>There we go! See how easy that was? Now get out of my airspace before I change my mind!" . "<c:Annie Yunque:44>¡Ya está! ¿Ves qué fácil? ¡Ahora largo de mi espacio aéreo antes de que cambie de opinión!")
("<c:Anvil Annie:44>I KNEW IT! Only goblin spies would refuse to pay! Time to blast some answers out of you!" . "<c:Annie Yunque:44>¡LO SABÍA! ¡Solo los espías goblin se negarían a pagar! ¡Hora de sacarte las respuestas a cañonazos!")
("<c:Anvil Annie:44>...That's a powerful warship you're flying. <B:0> <s:3>. . . . . <s:0> <B:0> Alright. New calculation. <B:0> If you wanted me dead, I'd already BE dead. And if you're hunting what I THINK you're hunting... <B:0> ...maybe I've been watching the wrong skies. <B:0> You gotta let me aboard, we should join up!" . "<c:Annie Yunque:44>...Eso es un buque de guerra poderoso el que pilotas. <B:0> <s:3>. . . . . <s:0> <B:0> Bien. Nuevo cálculo. <B:0> Si me quisieras muerta, ya ESTARÍA muerta. Y si estás cazando lo que CREO que estás cazando... <B:0> ...quizás he estado vigilando los cielos equivocados. <B:0> ¡Tienes que dejarme subir, deberíamos unirnos!")
("Welcome aboard!" . "¡Bienvenida a bordo!")
("Politely decline." . "Declinar amablemente.")
("<c:Anvil Annie:44>I'm sure we can find some space!" . "<c:Annie Yunque:44>¡Seguro que encontramos sitio!")
("Place block (1x2):" . "Colocar bloque (1x2):")
("<c:Anvil Annie:44>Finally aboard! Let me just... <B:0> <s:3>. . . <s:0>" . "<c:Annie Yunque:44>¡Por fin a bordo! Solo déjame... <B:0> <s:3>. . . <s:0>")
("<c:Anvil Annie:44>Wait. WAIT. <B:0> Those biosigns... <d:1000> <a:SHAKE>GOBLINS!? <B:0> I KNEW IT! This was a trap all along!" . "<c:Annie Yunque:44>Espera. ESPERA. <B:0> Esas bioseñales... <B:0> <d:1000> ¿¡<a:SHAKE>GOBLINS!? <B:0> ¡LO SABÍA! ¡Esto era una trampa desde el principio!")
("Anvil Annie has turned hostile!" . "¡Annie Yunque se ha vuelto hostil!")
("Anvil Annie joined your crew!" . "¡Annie Yunque se unió a tu tripulación!")
("<c:Anvil Annie:44>Understood, right. Hard to trust anyone, these days..." . "<c:Annie Yunque:44>Entendido, claro. Difícil fiarse de nadie, hoy en día...")
("<c:Anvil Annie:44>Your fortifications... That's not goblin salvage work. Human military refit. Maybe even pre-migration hardware. <B:0> 400@. Covert rates. <B:0> And you sail straight through - no loitering, no surveys, no 'equipment malfunctions' near my perimeter!" . "<c:Annie Yunque:44>Tus fortificaciones... Eso no es trabajo de chatarrero goblin. Reequipamiento militar humano. Quizás incluso material pre-migración. <B:0> 400@. Tarifa discreta. <B:0> ¡Y pasas de largo - nada de merodear, nada de reconocimientos, nada de 'averías del equipo' cerca de mi perímetro!")
("Pay 400@." . "Pagar 400@.")
("<c:Anvil Annie:44>...HA! Oh, that's <a:WAVE>PRECIOUS! <B:0> You actually thought - with THAT floating scrapyard - you could intimidate ME? <B:0> 800@ now. And count yourself lucky I don't raise it any higher!" . "<c:Annie Yunque:44>...¡JA! ¡Oh, qué <a:WAVE>GRACIOSO! <B:0> ¿De verdad pensaste - con ESE desguace flotante - que podías intimidarME? <B:0> 800@ ahora. ¡Y da gracias de que no lo suba más!")
("Pay 800@." . "Pagar 800@.")
("Refuse bribe." . "Rechazar soborno.")
("<c:Anvil Annie:44>Alright, let's negotiate. <B:0> I'm listening, but no sudden moves, gotit?" . "<c:Annie Yunque:44>Está bien, negociemos. <B:0> Te escucho, pero sin movimientos bruscos, ¿entendido?")
("Pay 700@." . "Pagar 700@.")
("Intimidate." . "Intimidar.")
("Intimidate. (risky)" . "Intimidar. (arriesgado)")
("Intimidate. (foolish)" . "Intimidar. (temerario)")
("<c:Anvil Annie:44>Unknown vessel! You're trespassing in MY airspace! <B:0> I've been keeping this stretch of sky clear for twenty years, and I don't plan on stopping now! <B:0> Don't even think about giving me that 'innocent trader' routine - I can smell goblin sympathizers from three leagues away!" . "<c:Annie Yunque:44>¡Nave desconocida! ¡Estás invadiendo MI espacio aéreo! <B:0> ¡Llevo veinte años manteniendo este tramo de cielo despejado, y no pienso parar ahora! <B:0> ¡Ni se te ocurra soltarme el numerito del 'comerciante inocente' - huelo a los simpatizantes goblin a tres leguas de distancia!")
("<c:Anvil Annie:44>Tell you what, spy - <B:0>you hand over 700@ right now, and maybe Sweet Bertha here won't blow a hole in your hull! (pats cannon)" . "<c:Annie Yunque:44>Te diré una cosa, espía - <B:0>¡me entregas 700@ ahora mismo, y quizás la dulce Bertha no te abra un boquete en el casco! (acaricia el cañón)")
("Negotiate." . "Negociar.")
("Refuse Bribe." . "Rechazar soborno.")
("We aren't spies!" . "¡No somos espías!")
("<c:Anvil Annie:44>Course you'd say that. Real spies always deny it. Innocent traders? They get confused, ask what I'm talking about. But you knew EXACTLY what I meant..." . "<c:Annie Yunque:44>Claro que dirías eso. Los espías de verdad siempre lo niegan. ¿Los comerciantes inocentes? Se confunden, preguntan de qué les hablo. Pero tú sabías EXACTAMENTE a qué me refería...")
("What's this debris field?" . "¿Qué son estos escombros?")
("<c:Anvil Annie:44>Spies, saboteurs, sleeper agents! They think they're so clever with their fake distress calls and forged cargo manifests! But I can spot 'em from leagues away! <B:0> See that scorched hull fragment? 'Friendly trader' who tried to scan my weapon configurations! <B:0> The nerve! They're ALL connected, part of some massive intelligence network! <B:0> Anyway..." . "<c:Annie Yunque:44>¡Espías, saboteadores, agentes durmientes! ¡Se creen muy listos con sus falsas llamadas de socorro y sus manifiestos de carga falsificados! ¡Pero yo los detecto a leguas! <B:0> ¿Ves ese fragmento de casco chamuscado? Un 'comerciante amigable' que intentó escanear mis configuraciones de armamento. <B:0> ¡Qué descaro! ¡TODOS están conectados, parte de una enorme red de inteligencia! <B:0> En fin...")
)
