'(("An ancient imperial missile platform contacts you and demands payment..." . "Una antigua plataforma de misiles imperial te contacta y exige un pago...")
("Your crew targets the station's external sensors with precision fire. <B:0> " . "Tu tripulación apunta a los sensores externos de la estación con fuego de precisión. <B:0> ")
("The weapons array remains active, but its targeting systems go dark. <B:0> " . "El arsenal de armas sigue activo, pero sus sistemas de puntería se apagan. <B:0> ")
("You slip past the blind station without incident." . "Pasas junto a la estación ciega sin incidentes.")
("Insufficient funds! The station begins charging its weapons!" . "¡Fondos insuficientes! ¡La estación comienza a cargar sus armas!")
("The station processes your payment. <B:0> " . "La estación procesa tu pago. <B:0> ")
("After a moment, it transmits a receipt datapacket to your systems." . "Tras un momento, transmite un paquete de datos con un recibo a tus sistemas.")
("Your crew examines the transmission: a properly formatted Imperial Transit Voucher, complete with authentication seals and tax filing instructions. <B:0> According to the attached guidance, this 600@ toll is fully deductible from your annual merchant levy... <B:0> ...which was last collected seventeen years ago." . "Tu tripulación examina la transmisión: un Comprobante de Tránsito Imperial debidamente formateado, con sellos de autenticación e instrucciones de declaración fiscal. <B:0> Según la guía adjunta, este peaje de 600@ es totalmente deducible de tu gravamen mercantil anual... <B:0> ...que se recaudó por última vez hace diecisiete años.")
("The station deactivates and allows you to pass." . "La estación se desactiva y te permite pasar.")
("Your crew examines the station more closely. <B:0> " . "Tu tripulación examina la estación más de cerca. <B:0> ")
("The toll demand references Imperial Transit Code section 47-G, subsection 12… <B:0> " . "La demanda de peaje hace referencia al Código de Tránsito Imperial sección 47-G, subsección 12… <B:0> ")
("…which was amended by decree 891 in the Third Solar Cycle… <B:0> " . "…que fue enmendado por el decreto 891 del Tercer Ciclo Solar… <B:0> ")
("…but that decree was suspended pending review after the empire fractured…" . "…pero dicho decreto fue suspendido pendiente de revisión tras la fragmentación del imperio…")
("Whether this toll is even legally enforceable would require months of archival research. <B:0> " . "Determinar si este peaje es siquiera legalmente exigible requeriría meses de investigación en archivos. <B:0> ")
("Your engineer has a simpler solution: physically disable the station's sensor array. <B:0> " . "Tu ingeniera tiene una solución más sencilla: desactivar físicamente la matriz de sensores de la estación. <B:0> ")
("It won't know you passed. But someone will eventually notice the damage…" . "No sabrá que pasaste. Pero alguien acabará notando el daño…")
("Disable the sensors?" . "¿Desactivar los sensores?")
("Sabotage it." . "Sabotearlo.")
("Just pay the toll." . "Pagar el peaje.")
("Refuse and fight!" . "¡Negarse y luchar!")
("While the old empire is now fragmented and most of its weapons systems are offline, this automated vessel seems to still be functioning. <B:0>The station's computers demand a toll of 600@. Pay?" . "Aunque el viejo imperio está fragmentado y la mayoría de sus sistemas de armas están fuera de servicio, esta nave automatizada parece seguir funcionando. <B:0>Los ordenadores de la estación exigen un peaje de 600@. ¿Pagar?")
("Pay 600@ toll." . "Pagar peaje de 600@.")
("Examine the station…" . "Examinar la estación…")
("Refuse." . "Rechazar.")
("The station begins charging its weapons!" . "¡La estación comienza a cargar sus armas!")
)
