'(("Your sensors detect some goblin scavengers returning from a raid. <B:0> Their leader excitedly waves you down, eager to trade their mysterious finds..." . "Tus sensores detectan a unos carroñeros goblin que regresan de una incursión. <B:0> Su líder te hace señas emocionado, ansioso por comerciar con sus misteriosos hallazgos...")
("Place first " . "Colocar primer ")
("Place second " . "Colocar segundo ")
("<c:Scavenger:35> Found thessse %s" . "<c:Carroñero:35> Encontré estosss %s")
(" on a human isssle!" . " ¡en una isssla humana!")
("... err ... Well, don't worry where I got them! <B:0>" . "... eeh ... ¡No te preocupesss de dónde los saqué! <B:0>")
(" Still working, barely sssinged! 1300@ for two, yesss? Better price than waiting for your workshop to build them!" . " ¡Todavía funcionan, apenas chamuscadosss! ¿1300@ por los dos, sssí? ¡Mejor precio que esperar a que tu taller los construya!")
("...but you don't ssseem to have enough. Do you want to sssalvage some stuff to come up with the fundsss? I'll check back in 15 secondsss?" . "...pero no parece que tengasss suficiente. ¿Quieresss desguazar algo para reunir los fondosss? ¿Vuelvo en 15 segundosss?")
("Purchase for 1300@." . "Comprar por 1300@.")
("Take by force." . "Tomar por la fuerza.")
("<c:Scavenger:35>Gah! Fine, take them! <B:0> Ssstolen from some fat merchantsss anyway... <B:0> But we won't forget thisss. We know where to find more friendsss..." . "<c:Carroñero:35>¡Gah! ¡Vale, llévatelos! <B:0> De todas formasss los robamos de unos comerciantesss gordos... <B:0> Pero no olvidaremosss esto. Sssabemos dónde encontrar más amigosss...")
("The goblins storm off, swearing vengeance..." . "Los goblins se largan furiosos, jurando venganza...")
("Decline offer." . "Rechazar oferta.")
("<c:Scavenger:35>Ssseems like you have enough now!" . "<c:Carroñero:35>¡Parece que ya tienesss suficiente!")
("<c:Scavenger:35>Sorry, that's not enough! Do you want to sssalvage some ssstuff to come up with the ressourcesss for payment? I'll check back in in 15 seconds?" . "<c:Carroñero:35>¡Lo sssiento, no es suficiente! ¿Quieresss desguazar algo para reunir los recursosss para el pago? ¿Vuelvo en 15 segundos?")
("<c:Scavenger:35>Yesss! Sssmart choice! Don't mind the burn marksss, they add character!" . "<c:Carroñero:35>¡Sssí! ¡Decisssión inteligente! ¡No te fijesss en las marcas de quemadura, le dan carácter!")
)
