'(("Some merchants broadcast an advertisement for advanced technology! Let's see if they have anything useful!" . "¡Unos comerciantes emiten un anuncio de tecnología avanzada! ¡Veamos si tienen algo útil!")
("<c:Merchant:7>We ordered too many %s and we're having a big sale today! Much cheaper than if you built them yourself. @ for two, what do you say?" . "<c:Comerciante:7>¡Pedimos demasiados %s y hoy tenemos una gran oferta! Mucho más barato que si los construyeras tú mismo. @ por dos, ¿qué dices?")
("Place first " . "Colocar primer ")
("Place second " . "Colocar segundo ")
("<c:Merchant:7>Looks great! You made a fine choice!" . "<c:Comerciante:7>¡Estupendo! ¡Buena elección!")
("<c:Merchant:7>Ok! I'll be here. Come see me again when you're ready! <B:0> (or use the START menu to return to the world map)" . "<c:Comerciante:7>¡Vale! Aquí estaré. ¡Vuelve cuando estés listo! <B:0> (o usa el menú START para volver al mapa del cielo)")
("<c:Merchant:7>Sorry, that's not enough! Do you want to salvage some stuff to come up with the resources for payment?" . "<c:Comerciante:7>¡Lo siento, no es suficiente! ¿Quieres desguazar algo para reunir los recursos para el pago?")
("<c:Merchant:7>Looks like you have enough now. <B:0> Buy two %s for %@?" . "<c:Comerciante:7>Parece que ya tienes suficiente. <B:0> ¿Comprar dos %s por %@?")
("<c:Merchant:7>Sorry, the price was %@, you're still %@ short…" . "<c:Comerciante:7>Lo siento, el precio era %@, aún te faltan %@…")
("Salvage more stuff…" . "Desguazar más cosas…")
("Exit." . "Salir.")
)
