'(("A Sylph supply depot appears through the clouds, its crystalline sensors tracking your approach. <B:0> Your radio crackles with a precise, emotionless transmission..." . "Un depósito de suministros sylph aparece entre las nubes, sus sensores cristalinos rastreando tu aproximación. <B:0> Tu radio crepita con una transmisión precisa y carente de emoción...")
("<c:Sylph Quartermaster:53>Scanning vessel configuration... <B:0> Analysis: sub-optimal armament for projected threat parameters in your operational zone. <B:0> Conclave logistics has authorized requisition of two % emplacements to your vessel. <B:0> Cost: materials only, %@." . "<c:Intendente Sylph:53>Escaneando configuración de la nave... <B:0> Análisis: armamento subóptimo para los parámetros de amenaza proyectados en vuestra zona operativa. <B:0> La logística del Cónclave ha autorizado la requisición de dos emplazamientos de % para vuestra nave. <B:0> Coste: solo materiales, %@.")
("Accept for %@." . "Aceptar por %@.")
("Refuse allocation." . "Rechazar asignación.")
("<c:Sylph Quartermaster:53>Acknowledged. Tactical assessment indicates 73% probability you will not survive the next three hostile encounters with current armament. <B:0> Your decision is... inefficient. <B:0> Requisition cancelled." . "<c:Intendente Sylph:53>Recibido. La evaluación táctica indica un 73% de probabilidad de que no sobreviváis los próximos tres encuentros hostiles con el armamento actual. <B:0> Vuestra decisión es... ineficiente. <B:0> Requisición cancelada.")
("Install first " . "Instalar primer ")
("Install second " . "Instalar segundo ")
("<c:Sylph Quartermaster:53>Transfer complete. Conclave tactical projections indicate improved survival probability. <B:0> Maintain operational readiness. Quartermaster out." . "<c:Intendente Sylph:53>Transferencia completa. Las proyecciones tácticas del Cónclave indican una probabilidad de supervivencia mejorada. <B:0> Mantened la disposición operativa. Intendente, fuera.")
("<c:Sylph Quartermaster:53>Standing by. Come see me again when you're ready! <B:0> (or use the START menu to return to the world map)" . "<c:Intendente Sylph:53>En espera. ¡Volved cuando estéis listos! <B:0> (o usad el menú START para volver al mapa del cielo)")
("<c:Sylph Quartermaster:53>Sorry, that's not enough! Do you want to salvage some stuff to come up with the resources for payment?" . "<c:Intendente Sylph:53>Insuficiente. ¿Deseáis desguazar material para reunir los recursos necesarios para el pago?")
("<c:Sylph Quartermaster:53>Looks like you have enough now. <B:0>Accept two %s for %@?" . "<c:Intendente Sylph:53>Parece que ahora disponéis de suficiente. <B:0>¿Aceptar dos %s por %@?")
("<c:Sylph Quartermaster:53>Sorry, the cost was %@, you're still %@ short…" . "<c:Intendente Sylph:53>El coste era %@, aún os faltan %@…")
("Salvage more stuff…" . "Desguazar más cosas…")
("Exit." . "Salir.")
)
