'(("You discover the wreckage of a goblin raid..." . "Descubres los restos de una incursión goblin...")
("Goblins from the surface! Now, they too inhabit the skies... nowhere is safe..." . "¡Goblins de la superficie! Ahora ellos también habitan los cielos... ningún lugar es seguro...")
("The island seems thoroughly ransacked... but the pirates inexplicably left behind a weapon. Haul it aboard?" . "La isla parece completamente saqueada... pero los piratas inexplicablemente dejaron un arma atrás. ¿Subirla a bordo?")
("Yeah!" . "¡Sí!")
("No, leave it." . "No, déjala.")
("What's a goblin raid?" . "¿Qué es una incursión goblin?")
("Looks like goblins from the surface world ransacked this island for scrap metal and fuel. It's unclear why they left a weapon lying around, perhaps they left in a hurry. <B:0> Anyway, pick up the weapon?" . "Parece que goblins del mundo de la superficie saquearon esta isla en busca de chatarra y combustible. No está claro por qué dejaron un arma tirada, quizás se fueron con prisa. <B:0> En fin, ¿recoger el arma?")
("Pick a slot (%x%)" . "Elige un espacio (%x%)")
("Like a missile-silo, but starts fires! A useful addition!" . "¡Como un silo de misiles, pero provoca incendios! ¡Una adición útil!")
("A special cannon that fires projectiles in a wide arc. How useful!" . "¡Un cañón especial que dispara proyectiles en un arco amplio! ¡Qué útil!")
("Wow, a very powerful weapon! <B:0> You're lucky to have found this..." . "¡Vaya, un arma muy poderosa! <B:0> Tienes suerte de haber encontrado esto...")
("Huh!? Who doesn't want free stuff? Suit yourself..." . "¿¡Eh!? ¿Quién rechaza algo gratis? Allá tú...")
)
