'(("A distress call sounds over your radio! <B:0> <b:/scripts/data/img/destroyed_town.img.bin>The remnants of a town appear, wrecked by war.." . "¡Una llamada de socorro suena en tu radio! <B:0> <b:/scripts/data/img/destroyed_town.img.bin>Los restos de un pueblo aparecen, destrozados por la guerra..")
("<c:Goblin Raider:39>Finally, sssomeone answered! <B:0> My raid crew left me behind when the town's defenssses were stronger than expected. <B:0> Got knocked out by some debris when their ion cannon hit us... By the time I came to, everyone wasss gone. _bitter_laugh_ Guesss they figured I was dead weight. <B:0> Would you have room for a more... reliable crew member?" . "<c:Asaltante Goblin:39>¡Por fin alguien contessstó! <B:0> Mi equipo de asalto me dejó atrás cuando las defenssas del pueblo fueron más fuertes de lo esperado. <B:0> Me noquearon unos escombros cuando su cañón iónico nos alcanzó... Para cuando desperté, ya no quedaba nadie. _risa_amarga_ Sssupongo que pensaron que era un essstorbo. <B:0> ¿Tendríasss sitio para una tripulante más... fiable?")
("She seems decent, invite her aboard?" . "Parece decente, ¿invitarla a bordo?")
("Welcome aboard!" . "¡Bienvenida a bordo!")
("Not today." . "Hoy no.")
("<c:Goblin Raider:39>Hold on, don't leave me here! I know your cassstle's full, but thisss island is burning!" . "<c:Asaltante Goblin:39>¡Essspera, no me dejesss aquí! ¡Sé que tu cassstillo está lleno, pero essta isla está ardiendo!")
("Place block (1x2):" . "Colocar bloque (1x2):")
("<c:Goblin Raider:39>Thanks for ressscuing me! I'll try to help out however I can!" . "<c:Asaltante Goblin:39>¡Graciasss por ressscatarme! ¡Intentaré ayudar en lo que pueda!")
("The goblin joined your crew!" . "¡La goblin se unió a tu tripulación!")
)
