'(("A distress call sounds over your radio! <B:0> <b:/scripts/data/img/destroyed_town.img.bin>The remnants of a town appear, wrecked by war.." . "¡Una llamada de socorro suena en tu radio! <B:0> <b:/scripts/data/img/destroyed_town.img.bin>Los restos de un pueblo aparecen, destrozados por la guerra..")
("<c:Girl:14>Heya! I'm so lucky someone showed up! Damned goblins took my whole village as hostages. Somehow I slept through the whole thing... Anyway, please take me with you! I promise not to get in the way!" . "<c:Chica:14>¡Hola! ¡Qué suerte que alguien apareció! Los malditos goblins se llevaron a toda mi aldea como rehenes. De alguna manera dormí durante todo el asunto... En fin, ¡por favor llévame contigo! ¡Prometo no estorbar!")
("She seems harmless, invite her aboard?" . "Parece inofensiva, ¿invitarla a bordo?")
("Sure!" . "¡Claro!")
("No." . "No.")
("Why let her aboard?" . "¿Por qué dejarla subir?")
("<c:Girl:14>Hmm.. well let's see. I'm good at cooking, I can clean your ship, I'm pretty decent at crochet and... I don't know if this is even relevant, but I'm a blackbelt in karate! <B:0> Can I come along?" . "<c:Chica:14>Hmm.. a ver. Se me da bien cocinar, puedo limpiar tu nave, soy bastante buena haciendo ganchillo y... no sé si esto es relevante, ¡pero soy cinturón negro en karate! <B:0> ¿Puedo ir con ustedes?")
("<c:Girl:14>.<d:500>.<d:500>.<d:500> Actually, I was wondering if you can do me one more small favor? I brought this data cartridge with an old photo of my village, can you hold onto it for me?" . "<c:Chica:14>.<d:500>.<d:500>.<d:500> En realidad, me preguntaba si puedes hacerme un pequeño favor más. Traje este cartucho de datos con una vieja foto de mi aldea, ¿puedes guardármelo?")
("Sadly, there's no room..." . "Lamentablemente, no hay espacio...")
("<c:Girl:14>Wait up a second, I know your castle's pretty full, but don't leave me here! This island is literally burning! I'll even sleep in a cargo bay..." . "<c:Chica:14>¡Espera un momento, sé que tu castillo está bastante lleno, pero no me dejes aquí! ¡Esta isla está literalmente ardiendo! Hasta dormiré en una bahía de carga...")
("Place cargo bay (1x2):" . "Colocar bahía de carga (1x2):")
("<c:Girl:14>Wait, you're serious! I guess I asked for it haha..." . "<c:Chica:14>¡Espera, lo dices en serio! Supongo que yo me lo busqué jaja...")
("The villager girl joined your crew!" . "¡La aldeana se unió a tu tripulación!")
)
