'(("A damaged fortress floats into view. The residents do not respond to your radio signals." . "Una fortaleza dañada aparece a la vista. Los residentes no responden a tus señales de radio.")
("You see a survivor amongst the wreckage. You cannot be sure whether the survivor is trustworthy. Invite survivor aboard?" . "Ves a un superviviente entre los escombros. No puedes estar seguro de si es de fiar. ¿Invitarlo a bordo?")
("Humans eaten: 17" . "Humanos devorados: 17")
("Days alone on island: lll" . "Días solo en la isla: lll")
("The survivor joined your crew!" . "¡El superviviente se unió a tu tripulación!")
("The survivor turned out to be very unfriendly!" . "¡El superviviente resultó ser muy hostil!")
("The survivor turned out to be a vicious goblin!" . "¡El superviviente resultó ser un goblin despiadado!")
("<c:Goblin:2>Die %!" . "<c:Goblin:2>¡Muere %!")
("Traitorsss" . "Traidoresss")
("Humansss" . "Humanosss")
("Sssylph ssscum" . "Esssoria sssylph")
("Sadly, there's no room..." . "Lamentablemente, no hay espacio...")
)
