'(("A damaged fortress floats into view. The residents do not respond to your radio signals." . "Una fortaleza dañada aparece a la vista. Los residentes no responden a tus señales de radio.")
("The island's radio appears to be broken. <B:0> Three survivors signal to you that they'd like to come aboard, but it's not clear whether they can be trusted. <B:0> Invite survivors aboard?" . "La radio de la isla parece estar rota. <B:0> Tres supervivientes te hacen señas de que les gustaría subir a bordo, pero no está claro si se puede confiar en ellos. <B:0> ¿Invitar a los supervivientes a bordo?")
("The survivors turned out to be vicious goblins, and their island is not as defenseless as it initially appeared..." . "Los supervivientes resultaron ser goblins despiadados, y su isla no estaba tan indefensa como parecía al principio...")
("<c:Goblin:2>Die %!" . "<c:Goblin:2>¡Muere %!")
("Traitorsss" . "Traidoresss")
("Humansss" . "Humanosss")
("Sssylph ssscum" . "Esssoria sssylph")
("Some of the survivors joined your crew!" . "¡Algunos de los supervivientes se unieron a tu tripulación!")
("The survivors joined your crew!" . "¡Los supervivientes se unieron a tu tripulación!")
)
