'(("An ancient warship approaches, flying a pirate flag. <B:0> The fortress gives off a strange radiation signature, but the pirates have not yet decided to attack..." . "Un antiguo buque de guerra se acerca, ondeando una bandera pirata. <B:0> La fortaleza emite una extraña firma de radiación, pero los piratas aún no han decidido atacar...")
("The pirates seem to have stolen a powerful imperial assault vessel. " . "Los piratas parecen haber robado un poderoso navío de asalto imperial. ")
("They demand %@ and make crude gestures. Will you pay?" . "Exigen %@ y hacen gestos groseros. ¿Pagarás?")
("Pay %@." . "Pagar %@.")
("No way!" . "¡Ni hablar!")
("What's an assault ship?" . "¿Qué es un navío de asalto?")
("Imperial assault ships were involved in the surface wars. Not many still exist, and not much is known about them. <B:0> The pirates are getting impatient. Pay the bribe?" . "Los navíos de asalto imperiales participaron en las guerras de la superficie. No quedan muchos, y no se sabe mucho sobre ellos. <B:0> Los piratas se están impacientando. ¿Pagar el soborno?")
("You cannot afford to pay. Prepare for heavy damage..." . "No puedes permitirte pagar. Prepárate para daños severos...")
("The pirates accept your bribe and move on." . "Los piratas aceptan tu soborno y siguen su camino.")
("Prepare for attack!" . "¡Prepárate para el ataque!")
)
