'(("A ship runs lit and steady against the dark, every system answering. <B:0> That is the first wrong thing. <B:0> The same figure stands at every window. One face, copied the length of the hull. <B:0> The nearest move and work. The farthest do not move at all. <B:0> Nothing hails you. The ship notes your approach, and a channel opens." . "Una nave navega iluminada y firme contra la oscuridad, con todos sus sistemas respondiendo. <B:0> Eso es lo primero que está mal. <B:0> La misma figura está en cada ventana. Un solo rostro, copiado a lo largo del casco. <B:0> Las más cercanas se mueven y trabajan. Las más lejanas no se mueven en absoluto. <B:0> Nada te llama. La nave registra tu aproximación, y se abre un canal.")
("The channel stays open. At the windows, the copies have stopped working — every one turned toward you." . "El canal permanece abierto. En las ventanas, las copias han dejado de trabajar — todas se han vuelto hacia ti.")
("We can spare someone." . "Podemos ceder a alguien.")
("Put it to rest." . "Darle descanso.")
("We can't help you." . "No podemos ayudarte.")
("You have no one left to give." . "No te queda nadie a quien ceder.")
("You bring your weapons to bear. The ship answers. <B:0> The nearest figures work the guns with the same blank diligence they showed at every other task — no anger in it. <B:0> The far ones do not move at all." . "Apuntas tus armas. La nave responde. <B:0> Las figuras más cercanas manejan los cañones con la misma diligencia vacía que mostraban en cualquier otra tarea — sin rabia alguna. <B:0> Las lejanas no se mueven en absoluto.")
("<c:Carrier:25>DEFENSE PROTOCOL ENGAGED. ASSETS COMMITTED." . "<c:Portadora:25>PROTOCOLO DE DEFENSA ACTIVADO. ACTIVOS COMPROMETIDOS.")
("Place item:" . "Coloca el objeto:")
("You got one '%'!" . "¡Has obtenido un '%'!")
("<c:Carrier:25>EXCHANGE COMPLETE. THE LEDGER IS BALANCED." . "<c:Portadora:25>INTERCAMBIO COMPLETADO. EL LIBRO MAYOR ESTA EQUILIBRADO.")
("Across the gap, your crewmate takes a place at the glass, and does not look back." . "Al otro lado del vacío, tu tripulante ocupa un lugar tras el cristal, y no mira atrás.")
("<c:Carrier:25>TEMPLATE ACCEPTED. PRODUCING FIRST COPY..." . "<c:Portadora:25>PLANTILLA ACEPTADA. PRODUCIENDO PRIMERA COPIA...")
("Something arrives in the bay — your crewmate's face, new and unworn." . "Algo llega a la bodega — el rostro de tu tripulante, nuevo y sin estrenar.")
("Replicant" . "Replicante")
("Something feels off. <B:0> Hm. Probably nothing." . "Algo no va bien. <B:0> Hm. No será nada.")
("The vessel falls away behind you, lit and steady as before. <B:0> At one window, a face you know presses to the glass. <B:0> By the next pass of the light, you can no longer pick it out from the rest." . "La nave se aleja tras de ti, iluminada y firme como antes. <B:0> En una de las ventanas, un rostro que conoces se aprieta contra el cristal. <B:0> Al siguiente paso de la luz, ya no puedes distinguirlo de los demás.")
("Pick a crewmember:" . "Elige a un tripulante:")
("<c:%:%> " . "<c:%:%> ")
("Crewmember" . "Tripulante")
("" . "")
("Are you sure? I will go if needed..." . "¿Estás seguro? Iré si hace falta...")
("Accept" . "Aceptar")
("Pick someone else" . "Elegir a otro")
("Nevermind" . "Olvídalo")
("<c:Carrier:25>CONTACT LOGGED. VESSEL VIABLE. <B:0> CREW INTEGRITY: 31%. GENERATION 1,408. THE LINE NO LONGER HOLDS FORM. <B:0> DESIGNATE ONE CREW MEMBER AS TEMPLATE. THE LINE WILL RESET TO GENERATION ZERO. <B:0> THE TEMPLATE REMAINS WITH THIS VESSEL. <B:0> A FIRST COPY IS ISSUED TO YOU, ALONG WITH A VALUABLE ITEM. <B:0> THE EXCHANGE IS EQUAL." . "<c:Portadora:25>CONTACTO REGISTRADO. NAVE VIABLE. <B:0> INTEGRIDAD DE LA TRIPULACION: 31%. GENERACION 1.408. LA LINEA YA NO CONSERVA SU FORMA. <B:0> DESIGNA A UN TRIPULANTE COMO PLANTILLA. LA LINEA SE REINICIARA A LA GENERACION CERO. <B:0> LA PLANTILLA PERMANECE CON ESTA NAVE. <B:0> SE TE ENTREGA UNA PRIMERA COPIA, JUNTO CON UN OBJETO VALIOSO. <B:0> EL INTERCAMBIO ES EQUITATIVO.")
)
