'(("An abandoned warship appears! <B:0> No crew seems to be aboard; the ship appears to be completely dormant..." . "¡Un buque de guerra abandonado aparece! <B:0> No parece haber tripulación a bordo; la nave parece estar completamente inactiva...")
("Take %…" . "Tomar %…")
("Place where?" . "¿Colocar dónde?")
("The fortress remains quiet.<B:0> Now to remove the next one..." . "La fortaleza permanece en silencio.<B:0> Ahora a retirar el siguiente...")
("<c:Abandoned Ship AI:25> .<d:500>.<d:500>.<d:500>.<d:500> " . "<c:IA de Nave Abandonada:25> .<d:500>.<d:500>.<d:500>.<d:500> ")
("PROCESSING INTERRUPT... <B:0> BLOCK DETECTED MISSING! " . "INTERRUPCIÓN DE PROCESO... <B:0> ¡BLOQUE AUSENTE DETECTADO! ")
("<B:0> HOSTILE THREAT DETECTED!" . "<B:0> ¡AMENAZA HOSTIL DETECTADA!")
("The vessel begins charging its weapons..." . "La nave comienza a cargar sus armas...")
("The ship's weapons seem to be more-or-less intact! Attempt to remove one?" . "¡Las armas de la nave parecen estar más o menos intactas! ¿Intentar retirar una?")
("nope" . "nel")
)
