'(("Through sheets of rain, you spot a fortress ahead... <B:0> Its walls are wrapped in writhing mycelium, organic patterns reaching toward the high windows... <B:0>" . "A través de cortinas de lluvia, divisas una fortaleza adelante... <B:0> Sus muros están envueltos en micelio serpenteante, patrones orgánicos que se extienden hacia los altos ventanales... <B:0>")
("From her twisted throne, the goblin queen studies you intently... <B:0> Your crew warns that those who refuse her demands rarely survive to regret it..." . "Desde su retorcido trono, la reina goblin te estudia con atención... <B:0> Tu tripulación advierte que quienes rechazan sus exigencias rara vez sobreviven para lamentarlo...")
("<c:Goblin Queen:40>#cackle# You're tressspasssing in my territory! " . "<c:Reina Goblin:40>#carcajada# ¡Estásss invadiendo mi territorio! ")
("I demand a tribute of %@! Pay!" . "¡Exijo un tributo de %@! ¡Paga!")
("I'll pay… (%@)" . "Pagaré… (%@)")
("No way!" . "¡Ni hablar!")
("Goblin Queen?" . "¿Reina Goblin?")
("It's said that she began as a promising Ashwalker Apprentice, studying ancient technology and surface lore. But where other monks sought to contain and guard dangerous artifacts, she saw opportunities for power. She began experimenting with forbidden technologies, particularly the controlled growth of mycelium... <B:0> What should we do?" . "Se dice que empezó como una prometedora aprendiz Ashwalker, estudiando tecnología antigua y el saber de la superficie. Pero donde otros monjes buscaban contener y custodiar artefactos peligrosos, ella vio oportunidades de poder. Comenzó a experimentar con tecnologías prohibidas, en particular el cultivo controlado de micelio... <B:0> ¿Qué hacemos?")
("<c:Goblin Queen:40>Thatsss not enough! Letsss sssee if theresss anything we can take!!" . "<c:Reina Goblin:40>¡¡Essso no es sssuficiente!! ¡¡Veamosss sssi hay algo que podamosss tomar!!")
("The Goblin Queen rejoices, having successfully extorted %@." . "La Reina Goblin se regocija, habiendo extorsionado %@ con éxito.")
("<c:Goblin Queen:40>UNACCEPTABLE!! PREPARE FOR BOARDING!!!" . "<c:Reina Goblin:40>¡¡¡INACEPTABLE!!! ¡¡¡PREPARAOSSS PARA EL ABORDAJE!!!")
("As victory draws near, the goblin queen slips away..." . "Cuando la victoria se acerca, la reina goblin se escabulle...")
)
