'(("An unexpected storm forces your island to retreat below the clouds... <B:0>" . "Una tormenta inesperada obliga a tu isla a retirarse bajo las nubes... <B:0>")
("Your scanners detect the presence of another island nearby... <B:0>" . "Tus escáneres detectan la presencia de otra isla cercana... <B:0>")
("Shielded by a powerful deflector field, the fortress appears immune to damage from the harsh surface atmosphere. <B:0>" . "Protegida por un poderoso campo deflector, la fortaleza parece inmune al daño de la hostil atmósfera de la superficie. <B:0>")
("They contact you offering assistance..." . "Te contactan ofreciendo asistencia...")
("<c:Scavenger:29>Hello! Having trouble there? <B:0> Fortunately for you, we have a large stockpile of spare deflector fields! Here, take this one!" . "<c:Chatarrero:29>¡Hola! ¿Problemas ahí? <B:0> ¡Por suerte para ti, tenemos una gran reserva de campos deflectores de repuesto! ¡Toma, quédate con este!")
("Place deflector (1x1)" . "Colocar deflector (1x1)")
("<c:Scavenger:29>Careful with that shield, it's very old and handmade! <B:0> " . "<c:Chatarrero:29>¡Cuidado con ese escudo, es muy antiguo y hecho a mano! <B:0> ")
("We've been living near the radioactive ash for a long time, and we've managed to coexist with it! Unfortunately, some others were not so lucky...<B:0>" . "¡Llevamos mucho tiempo viviendo cerca de la ceniza radiactiva, y hemos aprendido a coexistir con ella! Desafortunadamente, otros no tuvieron tanta suerte...<B:0>")
("We have to be moving on, good luck!" . "¡Tenemos que seguir adelante, buena suerte!")
)
