'(("An unusual structure emerges from the clouds... <B:0> A fortress of rough-hewn stone, adorned with crude but intricate carvings. <B:0> Inside, you spot goblin figures moving with unexpected discipline and precision..." . "Una estructura inusual emerge de las nubes... <B:0> Una fortaleza de piedra toscamente tallada, adornada con grabados rudos pero intrincados. <B:0> En su interior, divisas figuras goblin moviéndose con una disciplina y precisión inesperadas...")
("<c:Goblin Monk:41>We are the Ashwalker Order. While other goblins chase mere plunder, we seek the ancient strength that let our ancestors survive the surface world. <B:0> Our training could serve your crew well... for the right price." . "<c:Monje Goblin:41>Sssomosss la Orden Ashwalker. Mientras otros goblins persiguen el sssimple saqueo, nosotros buscamos la fuerza ancestral que permitió a nuestros antepasadosss sobrevivir en el mundo de la sssuperficie. <B:0> Nuestro entrenamiento podría ssserle útil a tu tripulación... por el precio adecuado.")
("Recruit? %@" . "¿Reclutar? %@")
("No thanks." . "No, gracias.")
("You cannot afford to pay. The monks become impatient, and cut the transmission." . "No puedes permitirte pagar. Los monjes se impacientan y cortan la transmisión.")
("<c:Goblin Monk:41>This is inconvenient, but I suppose we can help you out..." . "<c:Monje Goblin:41>Esssto es un inconveniente, pero sssupongo que podemos echarte una mano...")
("Place block (1x2):" . "Colocar bloque (1x2):")
("<c:Warrior Monk:41>I live to serve!" . "<c:Monje Guerrero:41>¡Vivo para ssservir!")
("The monk joined your crew!" . "¡El monje se unió a tu tripulación!")
("The Ashwalker Monk reluctantly hands over a datacart that he'd been keeping..." . "El monje Ashwalker entrega a regañadientes un cartucho de datos que había estado guardando...")
("The monks became angry, and cut the transmission." . "Los monjes se enfurecieron y cortaron la transmisión.")
)
