'(("High above the storm clouds, you notice a solitary watchtower drifting silently through the upper atmosphere... <B:0> A figure in bronze armor stands motionless at its peak, observing the chaos below with detached interest. <B:0> As you approach, they signal your fortress with precise, measured light pulses..." . "Muy por encima de las nubes de tormenta, divisas una torre de vigilancia solitaria flotando en silencio por la atmósfera superior... <B:0> Una figura con armadura de bronce permanece inmóvil en su cima, observando el caos abajo con interés distante. <B:0> Al acercarte, señalan tu fortaleza con pulsos de luz precisos y mesurados...")
("<c:Sylph Sentry:47>The patterns below grow more chaotic with each passing cycle. <B:0> My observations are complete. The archive has been updated. <B:0> My current assignment concludes with the approach of the storm front. <B:0> Your vessel appears... adequate for continued surveillance duties. <B:0>" . "<c:Centinela Sylph:47>Los patrones abajo se tornan más caóticos con cada ciclo que pasa. <B:0> Mis observaciones están completas. El archivo ha sido actualizado. <B:0> Mi asignación actual concluye con la llegada del frente de tormenta. <B:0> Vuestra nave parece... adecuada para labores de vigilancia continuada. <B:0>")
("I am trained in combat protocols and defensive systems analysis. <B:0> " . "Estoy entrenado en protocolos de combate y análisis de sistemas defensivos. <B:0> ")
("My people value knowledge above all else. Your journey may provide... useful data. <B:0>" . "Mi pueblo valora el conocimiento por encima de todo. Vuestro viaje podría proporcionar... datos útiles. <B:0>")
(" Do you require additional crew?" . " ¿Necesitáis tripulación adicional?")
("Recruit? %@" . "¿Reclutar? %@")
("No thanks." . "No, gracias.")
("You cannot afford to pay. The % becomes impatient, and cuts the transmission." . "No puedes permitirte pagar. El % se impacienta y corta la transmisión.")
("sentry" . "centinela")
("Sylph" . "sylph")
("<c:Sylph Sentry:47>You're out of space. This is inconvenient, but I suppose I can help you out..." . "<c:Centinela Sylph:47>No disponéis de espacio. Esto es inconveniente, pero supongo que puedo echaros una mano...")
("Place block (1x2):" . "Colocar bloque (1x2):")
("<c:Sylph Sentry:47> Acceptable. I am prepared to serve." . "<c:Centinela Sylph:47> Aceptable. Estoy preparado para servir.")
("The sentry joined your crew!" . "¡El centinela se unió a tu tripulación!")
("<c:Sylph Sentry:47>Understood. Safe travels." . "<c:Centinela Sylph:47>Entendido. Buen viaje.")
("her" . "su")
("she" . "ella")
("his" . "su")
("he" . "él")
("The figure returns to % vigil, bronze helmet gleaming in the cold light as % resumes silent vigil over the storms below..." . "La figura vuelve a % vigilia, el casco de bronce reluciendo bajo la luz fría mientras % retoma la vigilancia silenciosa sobre las tormentas abajo...")
)
