'(("You come upon the scene of a heated battle. <B:0> A goblin resource harvester vessel is attacking an unarmed village, its beams slicing through the town. <B:0> Noticing you, the goblins briefly stop attacking…" . "Te encuentras con una batalla encarnizada. <B:0> Una nave cosechadora de recursos goblin está atacando una aldea desarmada, sus rayos cortando el pueblo en pedazos. <B:0> Al notarte, los goblins dejan de atacar brevemente…")
("<c:Villager:5>We're being raided! That goblin ship over there is slicing chunks off of our town! <B:0> They just let the scrap fall to the ruined world below, where their friends collect the fallen resources. <B:0> I know it's a long shot, but any chance you could help us?" . "<c:Aldeano:5>¡Nos están saqueando! ¡Esa nave goblin de ahí está arrancando trozos de nuestro pueblo! <B:0> Dejan caer la chatarra al mundo arruinado de abajo, donde sus compinches recogen los restos. <B:0> Sé que es mucho pedir, pero ¿hay alguna posibilidad de que nos ayudes?")
("<c:Goblin:2> You think you can fight usss?! Hah!!" . "<c:Goblin:2> ¿¡Creesss que puedesss luchar contra nosotrosss?! ¡¡Jah!!")
("One of the villagers came aboard to help out!" . "¡Uno de los aldeanos subió a bordo para ayudar!")
("<c:Goblin:2> HAAHAH! You made the right choice, not helping those nasssty humansss!" . "<c:Goblin:2> ¡¡JAAJAJ!! ¡Hicisste bien en no ayudar a esosss asquerososs humanosss!")
("The goblins finish off the town, and share 1000@ of scrap with you." . "Los goblins acaban con el pueblo y comparten 1000@ de chatarra contigo.")
("Assist humans." . "Ayudar a los humanos.")
("Do nothing." . "No hacer nada.")
)
