'(("You come upon the scene of a heated battle. <B:0> A goblin resource harvester vessel is attacking an unarmed village, its beams slicing through the town. <B:0> Noticing you, the goblins briefly stop attacking…" . "Te encuentras con una batalla encarnizada. <B:0> Una nave cosechadora de recursos goblin está atacando una aldea desarmada, sus rayos cortando el pueblo en pedazos. <B:0> Al notarte, los goblins dejan de atacar brevemente…")
("<c:Goblin:2>You think you can fight usss?! Hah!!" . "<c:Goblin:2>¿¡Creesss que puedesss luchar contra nosotrosss?! ¡¡Jah!!")
("One of the villagers came aboard to help out!" . "¡Uno de los aldeanos subió a bordo para ayudar!")
("The goblins resume their attack. <B:0> " . "Los goblins retoman su ataque. <B:0> ")
("Maybe you weren't strong enough to face them anyway…" . "Quizás no eras lo bastante fuerte para enfrentarlos de todas formas…")
("<c:Villager:5>That goblin harvester is slicing chunks off of our town! They just let the scrap fall to the ruined world below, where their friends collect the fallen resources. Anyway, can you help??" . "<c:Aldeano:5>¡Esa cosechadora goblin está arrancando trozos de nuestro pueblo! Dejan caer la chatarra al mundo arruinado de abajo, donde sus compinches recogen los restos. En fin, ¿¡puedes ayudarnos!?")
("Sorry, but no." . "Lo siento, pero no.")
("<c:Villager:5>Oh! Just in time! Can you help us!? That goblin ship over there is very strong, but there's a chance you could defeat them..." . "<c:Aldeano:5>¡Oh! ¡Justo a tiempo! ¿¡Puedes ayudarnos!? Esa nave goblin de ahí es muy fuerte, pero hay una posibilidad de que puedas vencerlos...")
("Of course!" . "¡Por supuesto!")
("What's going on here?" . "¿Qué está pasando aquí?")
("Sorry, I can't help." . "Lo siento, no puedo ayudar.")
)
