'(("A nearby island seems to be transmitting an unusual distress signal..." . "Una isla cercana parece estar transmitiendo una señal de socorro inusual...")
("Upon closer inspection, you find that the castle may contain valuable cargo, but it's overgrown with mycelium. You can explore, although there's some risk of cross-contamination. Board anyway?" . "Al inspeccionarla de cerca, descubres que el castillo podría contener carga valiosa, pero está cubierto de micelio. Puedes explorar, aunque hay riesgo de contaminación cruzada. ¿Abordar de todos modos?")
("Let's explore!" . "¡Exploremos!")
("No way!" . "¡Ni hablar!")
("What's mycelium?" . "¿Qué es el micelio?")
("Mycelium is a substance that started infesting islands recently. It's pretty difficult to contain; some ships have a policy of burning infested islands on sight. Mycelium grows over the whole surface of an island, sucking a bit more power each time it grows larger. But it does have some defensive potential; when carefully contained, it can be useful as hull. <B:0> Anyway, should we board?" . "El micelio es una sustancia que ha empezado a infestar islas recientemente. Es bastante difícil de contener; algunas naves tienen como norma quemar las islas infestadas en cuanto las ven. El micelio crece por toda la superficie de una isla, absorbiendo un poco más de energía cada vez que se extiende. Pero tiene cierto potencial defensivo; si se contiene con cuidado, puede servir como casco. <B:0> En fin, ¿abordamos?")
("One of your crewmembers finds a data cartridge tangled in the fungal roots..." . "Uno de tus tripulantes encuentra un cartucho de datos enredado entre las raíces fúngicas...")
("While attempting to board, several spores on the castle burst, infesting your island with mycelium!" . "¡Al intentar abordar, varias esporas del castillo estallan, infestando tu isla con micelio!")
("You explore, and find cargo worth %@!" . "¡Exploras y encuentras carga valorada en %@!")
)
