'(("You come across an explorer's balloon, floating gently in the breeze. You adjust your engines to keep pace with it..." . "Te encuentras con el globo de un explorador, flotando suavemente en la brisa. Ajustas tus motores para seguirle el paso...")
("<c:Explorer:22>Hey there! You know, looks like we're going in the same direction! How about we join up?" . "<c:Explorador:22>¡Eh, hola! Oye, ¡parece que vamos en la misma dirección! ¿Qué tal si nos unimos?")
("He seems harmless, invite him aboard?" . "Parece inofensivo, ¿invitarlo a bordo?")
("Welcome aboard!" . "¡Bienvenido a bordo!")
("Sorry, but no." . "Lo siento, pero no.")
("Let's chat…" . "Charlemos…")
("<c:Explorer:22>I'm obsessed with finding new islands! When I find one, I mark it with a signal beacon. That's how you can find islands on your sky chart! Neat huh? <B:0> Anyway, can I come aboard?" . "<c:Explorador:22>¡Estoy obsesionado con encontrar nuevas islas! Cuando encuentro una, la marco con una baliza de señal. ¡Así es como puedes encontrar islas en tu carta del cielo! Genial, ¿eh? <B:0> En fin, ¿puedo subir a bordo?")
("The explorer joined your crew. Hungry, he ate 600@ of your food supplies!" . "El explorador se unió a tu tripulación. ¡Hambriento, devoró 600@ de tus provisiones!")
("Sadly, there's no room..." . "Lamentablemente, no hay espacio...")
("<c:Explorer:22>No room in your castle? Hold on, I've got some supplies, I'll help out..." . "<c:Explorador:22>¿No hay sitio en tu castillo? Espera, tengo algunos materiales, te echo una mano...")
("Place ladder (1x2):" . "Colocar escalera (1x2):")
("<c:explorer:22>Thanks! I'll try to help out however I can!" . "<c:Explorador:22>¡Gracias! ¡Intentaré ayudar en lo que pueda!")
("The explorer joined your crew!" . "¡El explorador se unió a tu tripulación!")
)
