'(("You spot strange flares arcing between the clouds... <B:0> A lone goblin perches atop a makeshift balloon, studying the patterns of island movements!" . "Divisas extrañas bengalas trazando arcos entre las nubes... <B:0> ¡Un goblin solitario se encarama sobre un globo improvisado, estudiando los patrones de movimiento de las islas!")
("<c:Spotter:45>Sssaw your ship from my watching post! Been tracking island pathsss, marking which ones are ripe for raiding. Know all the bessst hunting groundsss!" . "<c:Vigía:45>¡Vi tu nave dessde mi puessto de vigilancia! Llevo rastreando rutasss de islasss, marcando cuálesss están maduras para sssaquear. ¡Conozco losss mejoresss cotos de caza!")
("He seems harmless, invite him aboard?" . "Parece inofensivo, ¿invitarlo a bordo?")
("Welcome aboard!" . "¡Bienvenido a bordo!")
("Sorry, but no." . "Lo siento, pero no.")
("Let's chat…" . "Charlemos…")
("<c:Spotter:45>When rich islandsss passs overhead, I track their movement patterns. Could show you where the fat merchantsss like to hide... <B:0> Need a ssspotter on your crew?" . "<c:Vigía:45>Cuando las islasss ricasss pasan por encima, rastreo susss patrones de movimiento. Podría enseñarte dónde les gussta esconderse a losss comerciantesss gordosss... <B:0> ¿Necesitáisss un vigía en la tripulación?")
("Explain your goggles?" . "¿Qué hay de tus gafas?")
("<c:Spotter:45>Ohhh! These ssspecial goggles are necesssary! <B:0> It's so bright when staring out at the cloudsss, without this visor, I'd go sssun-blind! <B:0> Anyway, I've got lotsss of experience, need a ssspotter?" . "<c:Vigía:45>¡Ohhh! ¡Estasss gafasss especialesss son necesariasss! <B:0> ¡Hay tanta luz cuando mirasss lasss nubesss, sssin esta visera me quedaría ciego del sssol! <B:0> En fin, tengo mucha experiencia, ¿necesitáisss un vigía?")
("<c:Crew:%> Captain! Thisss one hasss been hiding sssomething! Found thisss cart sssstashed in his bunk. Could be sssecret codes, maybe he'sss a double agent! It saysss 'do NOT read'!!" . "<c:Tripulación:%> ¡Capitán! ¡Esste ha essstado escondiendo algo! ¡Encontré esste cartucho esscondido en su litera! ¡Podrían ssser códigosss sssecretosss, quizás es un agente doble! ¡¡Dice 'NO leer'!!")
("<c:Spotter:45> That wasss PRIVATE!" . "<c:Vigía:45> ¡Essso era PRIVADO!")
("(The spotter hisses something unprintable and climbs to his lookout post, although one of your crew thinks he saw him carrying a pen and a few sheets of paper...)" . "(El vigía sisea algo irrepetible y trepa a su puesto de vigilancia, aunque uno de tus tripulantes cree haberlo visto llevando una pluma y unas hojas de papel...)")
("The spotter joined your crew. Hungry, he ate 600@ of your food supplies!" . "El vigía se unió a tu tripulación. ¡Hambriento, devoró 600@ de tus provisiones!")
("Sadly, there's no room..." . "Lamentablemente, no hay espacio...")
("<c:Spotter:45>No room in your castle? Hold on, I've got some supplies, I'll help out..." . "<c:Vigía:45>¿No hay sssitio en tu cassstillo? Essspera, tengo algunos materialesss, te echo una mano...")
("Place ladder (1x2):" . "Colocar escalera (1x2):")
("<c:Spotter:45>Thanks! I'll try to help out however I can!" . "<c:Vigía:45>¡Graciasss! ¡Intentaré ayudar en lo que pueda!")
("The spotter joined your crew!" . "¡El vigía se unió a tu tripulación!")
)
