;;;
;;; power_balance_2.lisp
;;;


(terrain-set (player) 5)
(island-configure
 (player)
 '((infirmary 0 13)
   (workshop 2 11)
   (power-core 2 13)
   (cannon 4 12)
   (cannon 4 13)
   (cannon 4 14)
   (cannon 4 11)))


(chr-new (player) 1 14 'neutral nil)


(opponent-init 4 'hostile)

(island-configure
 (opponent)
 '((power-core 1 13)))


(autopilot
 '((500 nil)
   (100 "<c:Milo:5>In one of the earlier tutorials about Power Balance, we explained the importance of building enough power to supply all of the systems on your island. <B:0> The Beginner difficulty setting allows you to disable unused blocks, allowing us to reclaim power without salvaging them. <B:0> By opening the SELECT menu on certain blocks, we can deactivate them, allowing us to use the energy for something else instead.")
   (1219 Select)
   (100 Select)
   (1903 Right)
   (400 Right)
   (450 Right)
   (417 Right)
   (567 Select)
   (584 Right)
   (350 Right)
   (901 A)
   (1584 Select)
   (500 Right)
   (300 Right)
   (801 A)
   (500 nil)
   (100 "<c:Milo:5>Opening the SELECT menu on individual blocks isn't the only way to regulate power usage. <B:0> By opening the select menu on a power supply, and selecting 'divert power', you can adjust activate and deactivate multiple blocks at once!")
   (2521 Left)
   (584 Up)
   (467 Select)
   (1068 Right)
   (183 Right)
   (150 Right)
   (1553 A)
   (985 Left)
   (417 Left)
   (484 A)
   (417 Right)
   (283 Right)
   (267 Right)
   (317 A)
   (150 Up)
   (234 A)
   (183 Up)
   (200 A)
   (1185 Down)
   (183 Down)
   (133 Down)
   (200 Down)
   (367 A)
   (968 Up)
   (284 A)
   (100 Up)
   (217 A)
   (100 Up)
   (267 A)
   (116 Left)
   (233 Down)
   (283 Left)
   (217 Left)
   (117 Down)
   (49 Left)
   (350 A)
   (1536 B)
   (600 nil)
   (100 "<c:Milo:5>You may have noticed, some the blocks in the 'divert power' menu were labeled with a blue circle icon. These are the blocks that can be deactivated. All blocks in the 'weapons' category of the glossary, and many of the blocks in the 'misc' category, can be deactivated! <B:0> If a block sits unused for a long time, you may want to think about salvaging it instead to use the resources to build something else...")))
