'(("You arrive at a busy trading port. " . "Llegas a un concurrido puerto comercial. ")
("Some merchants broadcast a message asking for assistance..." . "Unos comerciantes emiten un mensaje pidiendo asistencia...")
("<c:Merchant:7>We promised to deliver some cargo to our customers, but with this storm approaching, we don't think we can make the delivery. Can you help? We'll pay you a bit upfront, and I'm sure that they'll tip you generously." . "<c:Comerciante:7>Prometimos entregar algo de carga a nuestros clientes, pero con esta tormenta acercándose, no creemos poder hacer la entrega. ¿Puedes ayudar? Te pagaremos un poco por adelantado, y seguro que te darán una buena propina.")
("I accept!" . "¡Acepto!")
("Sorry, but no." . "Lo siento, pero no.")
("Explain deliveries?" . "¿Explicar las entregas?")
("<c:Merchant:7>Usually we have stuff delivered by balloon. Customers place orders, and we send then out by airship. But with this terrible weather coming in, it's too risky to send anything. Can you help us out?" . "<c:Comerciante:7>Normalmente hacemos las entregas por globo. Los clientes hacen pedidos, y los enviamos por aeronave. Pero con este tiempo tan horrible que se avecina, es demasiado arriesgado enviar nada. ¿Puedes echarnos una mano?")
("parcel" . "paquete")
("<c:Merchant:7>Wonderful! I'll mark the address with an * on your sky chart!" . "<c:Comerciante:7>¡Maravilloso! ¡Marcaré la dirección con un * en tu carta del cielo!")
("Amazed by the picturesque view from the market center, one of your crew members took a photo, and recorded it on a data cartridge..." . "Maravillado por la pintoresca vista desde el centro del mercado, uno de tus tripulantes sacó una foto y la grabó en un cartucho de datos...")
("<c:Merchant:7>Oh, I'm so sorry! I just got a call from the customer, she had to relocate to flee the storm. Here's 400@ for your trouble." . "<c:Comerciante:7>¡Oh, lo siento mucho! Acabo de recibir una llamada de la clienta, tuvo que mudarse para huir de la tormenta. Aquí tienes 400@ por las molestias.")
("<c:Merchant:7>I understand... I guess we'll try to find someone else..." . "<c:Comerciante:7>Entiendo... supongo que intentaremos encontrar a alguien más...")
)
