'(("A nearby farming colony requests assistance..." . "Una colonia agrícola cercana solicita asistencia...")
("<c:Farmer Meyer:9>Looks like a bad storm's coming this way! Hey, I have an idea! How about you do me a favor and relocate my orchard of lemon trees to my brother's island... I'll tell him to pay you 1400@ for each one that you successfully deliver!" . "<c:Granjero Meyer:9>¡Parece que viene una tormenta fuerte para acá! ¡Eh, tengo una idea! ¿Qué tal si me haces un favor y trasladas mi huerto de limoneros a la isla de mi hermano... Le diré que te pague 1400@ por cada uno que entregues con éxito!")
("<c:Farmer Meyer:9>Please take good care of them! I marked my brother's address on your sky chart with an *!" . "<c:Granjero Meyer:9>¡Por favor cuídalos bien! ¡Marqué la dirección de mi hermano en tu carta del cielo con un *!")
("<c:Farmer Meyer:9>Anything else you'd like to discuss?" . "<c:Granjero Meyer:9>¿Algo más de lo que quieras hablar?")
("Farming?" . "¿Agricultura?")
("<c:Farmer Meyer:9>Farms up here grow crops cultivated for cold air. Even so, nothing would grow at this altitude without heat from the island reactor core..." . "<c:Granjero Meyer:9>Las granjas aquí arriba cultivan cosechas adaptadas al aire frío. Aun así, nada crecería a esta altitud sin el calor del núcleo reactor de la isla...")
("Irrigation?" . "¿Irrigación?")
("<c:Farmer Meyer:9>Although we do get some light rain up here, it's not enough for growing crops. But we can harvest water from the clouds, of course..." . "<c:Granjero Meyer:9>Aunque sí nos llega algo de lluvia ligera aquí arriba, no es suficiente para cultivar. Pero podemos recolectar agua de las nubes, por supuesto...")
("Nope!" . "¡No!")
("<c:Farmer Meyer:9>Good luck!" . "<c:Granjero Meyer:9>¡Buena suerte!")
("<c:Farmer Meyer:9>I was going to ask you to help relocate some of these lemon trees, but the storm's getting closer and I need to move out! Maybe we'll meet again, someday..." . "<c:Granjero Meyer:9>Iba a pedirte que ayudaras a trasladar algunos de estos limoneros, ¡pero la tormenta se acerca y tengo que irme! Quizás nos volvamos a encontrar algún día...")
)
