'(("A small village specializing in ceramics offers to sell you a batch of ornate tiles. Your crew insists that you'll be able to resell the tiles at another village for a much higher price..." . "Una pequeña aldea especializada en cerámica se ofrece a venderte un lote de azulejos ornamentados. Tu tripulación insiste en que podrás revenderlos en otra aldea por un precio mucho mayor...")
("<c:Merchant:7>So, whaddya say? Purchase a batch of ceramics for %@?" . "<c:Comerciante:7>Bueno, ¿qué dices? ¿Compras un lote de cerámica por %@?")
("OK!" . "¡Vale!")
("No thanks." . "No, gracias.")
("ceramic tiles" . "azulejos")
("<c:Merchant:7>Great, here are your tiles!" . "<c:Comerciante:7>¡Genial, aquí tienes tus azulejos!")
("(After talking with your crew, you mark the location of a town on your sky chart with an *)" . "(Después de hablar con tu tripulación, marcas la ubicación de un pueblo en tu carta del cielo con un *)")
("<c:Merchant:7>Oh, I'm so sorry! We can't actually sell you anything today." . "<c:Comerciante:7>¡Oh, lo siento mucho! La verdad es que hoy no podemos venderte nada.")
("<c:Merchant:7>No problem!" . "<c:Comerciante:7>¡No hay problema!")
)
