;;;
;;; quest_marker/civ.lisp
;;;



(dialog "You reach the location marked by the child. <B:0> "
        "A goblin stronghold materializes ahead - a patchwork fortress of stolen materials and makeshift defenses. Despite its rough appearance, the settlement is clearly well-defended and bustling with activity...")


(opponent-init 9 'neutral)


(island-configure
 (opponent)
 '((hull 0 7)
   (mycelium 0 8)
   (mycelium 0 11)
   (energized-hull 0 10)
   (mycelium 0 9)
   (mycelium 0 6 40)
   (mycelium 0 14)
   (mycelium 0 12)
   (mycelium 0 13)
   (mycelium 1 12)
   (mycelium 1 14)
   (mycelium 1 6)
   (mycelium 1 7 40)
   (mycelium 1 11)
   (hull 1 13)
   (hull 1 10)
   (hull 1 8)
   (hull 1 9)
   (power-core 2 9)
   (mycelium 2 5)
   (energized-hull 2 13)
   (energized-hull 2 12)
   (mycelium 2 7)
   (energized-hull 2 14)
   (mycelium 2 6)
   (hull 2 11)
   (hull 2 8)
   (hull 3 8)
   (stairwell 3 11)
   (mycelium 3 7)
   (hull 3 6)
   (mycelium 3 5)
   (power-core 4 10)
   (mycelium 4 7)
   (stacked-hull 4 9)
   (mycelium 4 8)
   (mycelium 4 5)
   (mycelium 4 6)
   (reactor 4 12)
   (stacked-hull 5 9)
   (mycelium 5 8)
   (mycelium 5 7)
   (stairwell 6 11)
   (mycelium 6 6)
   (infirmary 6 9)
   (mycelium 6 7)
   (hull 6 8)
   (missile-silo 7 7)
   (transporter 7 13)
   (forcefield* 7 6)
   (transporter 7 11)
   (mycelium 8 8)
   (mycelium 8 7)
   (mycelium 8 6)
   (transporter 8 13)
   (transporter 8 11)
   (stacked-hull 8 10)
   (mycelium 8 9)))


(flag-show (opponent) flag-id-pirate)


(let ((id (lookup 6 qvar))
      (child nil))
  (map (lambda (chr)
         (if (equal id (lookup 'id (cddr chr)))
             (setq child true)))
       (chrs (player)))
  (if child
      (defn on-converge ()
        (dialog "<c:Goblin Chieftain:42>Who approachesss our territory? <B:0> Sssylph!? State your businessss!")
        (defn on-dialog-closed ()
          (dialog "<c:Goblin Child:50>Father! FATHER! It'sss me!")
          (defn on-dialog-closed ()
            (dialog "<c:Goblin Chieftain:42>My ssson! <B:0> We thought... when the retreat signal came and you weren't aboard... <B:0> #pauses, looking between child and you# You brought him back.")
            (defn on-dialog-closed ()
              (map (lambda (chr)
                     (if (equal id (lookup 'id (cddr chr)))
                         (chr-del (player) (car chr) (cadr chr))))
                   (chrs (player)))
              (coins-add 2000)
              (adventure-log-add 55 nil)
              (dialog "<c:Goblin Chieftain:42>#studies you carefully# ...I don't undersstand your reasonsss, Sssylph. But my ssson is alive. That'sss what matters.")
              (defn on-dialog-closed ()
                (dialog "<c:Goblin Chieftain:42>Here. #gestures to raiders who bring forward supplies# Payment. We pay our debtsss, even to Sssylph. <B:0> But don't expect thisss to change anything between our people. One act doesn't erase centuriesss.")
                (setq on-dialog-closed nil)
                (defn on-dialog-closed ()
                  (dialog "The goblins have also gifted you a salvaged power supply! Where do you want to place it?")
                  (setq on-dialog-closed nil)
                  (run-util-script "place-new-block"
                                   'chaos-core
                                   "Place chaos-core:"
                                   (lambda (x y)
                                     (exit)))))))))

      (defn on-converge ()
        (dialog "You arrive at the goblin settlement, but the child is no longer aboard your island. The goblins eye your fortress with suspicion and hostility...")
        (exit))))
