'(("View Controls" . "Ver Controles")
("Edit Controls" . "Editar Controles")
("Save new controls?" . "¿Guardar nuevos controles?")
("Restore Defaults" . "Restaurar Valores")
("What would you like to do?" . "¿Qué deseas hacer?")
("Change Language" . "Cambiar Idioma")
("Really change language to '%'?" . "¿Cambiar idioma a '%'?")
("Pick a language:" . "Elige un idioma:")
("Disable Lighting Effects" . "Desactivar Efectos de Luz")
("Enable Lighting Effects" . "Activar Efectos de Luz")
("Dynamic lighting graphical effects %" . "Efectos gráficos de iluminación dinámica %")
("Disable Rumble" . "Desactivar Vibración")
("Enable Rumble" . "Activar Vibración")
("Rumble %" . "Vibración %")
("enabled!" . "¡activado!")
("disabled!" . "¡desactivado!")
("Exit" . "Salir")
)
