'(("Introduction" . "Introducción")
("Game Speed" . "Velocidad de Juego")
("Weapon Groups" . "Grupos de Armas")
("Firing Patterns" . "Patrones de Disparo")
("Target Queueing" . "Cola de Objetivos")
("Salvage" . "Desguace")
("Moving Blocks" . "Mover Bloques")
("Construction Tricks" . "Trucos de Construcción")
("Advanced Structures" . "Estructuras Avanzadas")
("Your Crew" . "Tu Tripulación")
("Replicators" . "Replicadores")
("Transporters" . "Transportadores")
("Portals" . "Portales")
("Adding Terrain" . "Añadir Terreno")
("Power Balance" . "Balance de Energía")
("Diverting Power" . "Desviar Energía")
)
