'(("While out on reconnaissance, your crew discovers an overcrowded transit hub, full of refugees departing the storm... <B:0> " . "Durante una misión de reconocimiento, tu tripulación descubre un centro de tránsito abarrotado, lleno de refugiados huyendo de la tormenta... <B:0> ")
("In the local cantina, a mysterious traveller offers you a deal... <B:0> You change course to dock with the station..." . "En la cantina local, un misterioso viajero te ofrece un trato... <B:0> Cambias de rumbo para atracar en la estación...")
("<c:Traveller:23> Hello! I was just talking to your crew! A few weeks ago, some wretched goblins ransacked my island. Outnumbered, I jumped in a transporter and ended up here. Can you help me get back home?" . "<c:Viajero:23> ¡Hola! ¡Estaba hablando con tu tripulación! Hace unas semanas, unos malditos goblins saquearon mi isla. En inferioridad numérica, salté a un transportador y acabé aquí. ¿Puedes ayudarme a volver a casa?")
("Of course!" . "¡Por supuesto!")
("I'm kind of busy…" . "Estoy un poco ocupado…")
("<c:Traveller:23>Oh! It looks like you're out of room! Let me fix that..." . "<c:Viajero:23>¡Oh! ¡Parece que no tienes sitio! Déjame arreglarlo...")
("Place block (1x2):" . "Colocar bloque (1x2):")
("<c:Traveller:23>Great! I'll come aboard and travel to the destination with you! I've marked the location on your sky chart with an *..." . "<c:Viajero:23>¡Genial! ¡Subiré a bordo y viajaré al destino contigo! He marcado la ubicación en tu carta del cielo con un *...")
("<c:Traveller:23>Looking at your sky chart, doesn't seem like we can get there before the storm overtakes us. I'll join your crew anyway, better than waiting in line for a transporter here..." . "<c:Viajero:23>Mirando tu carta del cielo, no parece que podamos llegar antes de que la tormenta nos alcance. Me uniré a tu tripulación de todos modos, mejor que esperar en la cola de un transportador aquí...")
("The mysterious traveller joined your crew!" . "¡El misterioso viajero se unió a tu tripulación!")
)
